export const fito = [
    {
        ID: 1,
        Fitoterapicos: "Abacateiro\r\n",
        Nomebot: "Persea persea\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Extrato\/Decocção\/Tintura\r\n",
        Posologia: "Extrato Seco: 500 mg 2 x ao dia.\nExtrato Fluído: 2 a 10 ml ao dia.\nTintura: 10 a 50 ml dia. \/ \nDecocção da folha e fruto: 20g\/l tomar 200 ml a cada 6-8 horas.",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Ação diurética colagoga e antiflatulenta.\r\n",
        ContraInd: "Pacientes em tratamento com varfarina (anticoagulante). Gestantes por promover contrações e aborto.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não utilizar em pacientes que desejam emagrecer devido ao alto teor calórido.\r\n"
    },
    {
        ID: 2,
        Fitoterapicos: "Alcachofra\r\n",
        Nomebot: "Cynara scolymus\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 2 g (1 col sobremesa) em 150mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá 3 x ao dia. \nExtrato\/tintura: 7,5 a 12,5 mg de derivados de ácido cafeoilquínico expressos em ácido clorogênico",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dispepsia (distúrbios da digestão), Colerético, colagogo.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas com doenças da vesícula biliar. Usar cuidadosamente em pessoas com hepatite grave, falência hepática e câncer hepático.\r\n",
        Efeitos: "O uso pode provocar flatulência (gases), fraqueza e sensação de fome\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 3,
        Fitoterapicos: "Alcaçuz\r\n",
        Nomebot: "Glycyrrhiza glabra\r\n",
        PartUtilizada: "Raiz\r\n",
        FormUtilizacao: "Infusão: 4,5 g (1 ½ col sopa) em 150 ml (xíc chá)\r\n",
        Posologia: "Utilizar 1 xíc de chá 3-4 x ao dia.\nExtratos\/ tinturas: 60 a 200 , g de ácido glicirrizínico (expectorante); 200 a 600 mg de ácido clicirrizínico (úlceras\ngástricas e duodenais).\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Tosses, gripes e resfriados. Expecorante, coadjuvante no tratamento de úlceras gástrica e duodenais.\r\n",
        ContraInd: "Não deve ser utilizado na gravidez e pessoas com hipertensão arterial, hiperestrogenismo e diabetes. Não utilizar contuamente por mais de seis semanas sem acompanhamento médico.\r\n",
        Efeitos: "Possível quadro de pseudoaldosteronismo por ação mineralocorticóide (caracterizado por retenção de sódio, cloro e água, edema, hipertensão arterial e ocasionalmente mioglobinúria)\r\n",
        InfoAdic: "Deve haver cautela ao associar com anticoagulantes, corticóides e antiinflamatórios\r\n"
    },
    {
        ID: 4,
        Fitoterapicos: "Alecrim\r\n",
        Nomebot: "Rosmarinus officinalis\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 3-6 g (1-2 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Oral : Utilizar de 1 a 2 xíc chá ao dia \/ \nTópico : Aplicar no local afetado 2 x ao dia.\n",
        Via: "Oral e Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Oral: Dispepsia (distúrbios digestivos).\nTópico: Distúrbios circulatórios, como anti-séptico e cicatrizante",
        ContraInd: "\"Não deve ser utilizado por pessoas com doença prostática, gastroenterites, dermatoses em geral e om histórico de\nconvulsão.\"\r\n",
        Efeitos: "Usado cronicamente, ou em doses excessivas, pode causar irritação renal e gastrointestinal\r\n",
        InfoAdic: "Não constam\r\n"
    },
    {
        ID: 5,
        Fitoterapicos: "Alecrim-pimenta\r\n",
        Nomebot: "Lippia sidoides\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 2-3 g (2-3 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Aplicar de 2 a 3 x ao dia\r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Gargarejos, bochechos e lavagens. Inflamações da boca e garganta, como anti-séptico.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não deve ser usado em inalações devido à ação irritante dos vapores. Não engolir o produto após o bochecho e gargarejo\r\n"
    },
    {
        ID: 6,
        Fitoterapicos: "Alho\r\n",
        Nomebot: "Allium sativum\r\n",
        PartUtilizada: "Bulbo\r\n",
        FormUtilizacao: "Maceração: 0,5 g (1 col café) em 30 mL (cálice)\r\n",
        Posologia: "Maceração: Utilizar 1 cálice 2 x ao dia antes das refeições.\nExtratos\/tintura\/óleo: Dose diária de 2,7 a 4,1 mg de alicina.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Hipercolesterolemia (colesterol elevado). Coadjuvante no tratamento da hiperlipidemia e hipertensão arterial leve, auxiliar na prevenção da aterosclerose. Atua como expectorante e anti-séptico.\r\n",
        ContraInd: "Não deve ser utilizado por menores de três anos e pessoas com gastrite e úlcera gástrica, hipotensão (pressão baixa) e hipoglicemia. (concentração de açúcar baixo no sangue). Não utilizar em caso de hemorragia e em tratamento com anticoagulantes.\r\n",
        Efeitos: "Doses acima da recomendada podem causar desconforto gastrointestinal.\r\n",
        InfoAdic: "Descontinuar o uso 10 dias antes de qualquer cirurgia. Deixar a droga seca rasuradapor cerca de uma hora em maceração.\r\n"
    },
    {
        ID: 7,
        Fitoterapicos: "Anis estrelado\r\n",
        Nomebot: "Illicium verum\r\n",
        PartUtilizada: "Frutos\r\n",
        FormUtilizacao: "Infusão: 1,5 g (1 ½ col de chá) em 150 ml (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc de chá 3-4 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Bronquite como expectorante.\r\n",
        ContraInd: "Não utilizar na gravidez e no hiperestrogenismo.\r\n",
        Efeitos: "O uso pode ocasionar reações de hipersensibilidade cutânea, respiratória e gastrintestinal\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 8,
        Fitoterapicos: "Anis, Erva doce\r\n",
        Nomebot: "Pimpinela anisum\r\n",
        PartUtilizada: "Frutos\r\n ",
        FormUtilizacao: "Decocção: 1,5 g (3 col café) em 150 mL água (xíc chá).\r\n",
        Posologia: "Decocção: Utilizar 1 xíc chá 3x ao dia.\nExtratos\/tintura: 0-1 ano: 16 a 45 mg de trans-anetol; 1-4 anos: 32 a 90 mg de trans-anetol; adultos: 80 a 225 mg transanetol.\n\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Dispepsia (distúrbios digestivos), cólicas gastrointestinais e como expectorante, antiespasmódico, carminativo.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "A droga vegetal deve ser amassada imediatamente antes de usar\r\n"
    },
    {
        ID: 9,
        Fitoterapicos: "Arnica\r\n",
        Nomebot: "Zingiber officinale\r\n",
        PartUtilizada: "Flores, Capítulo floral\r\n",
        FormUtilizacao: "Infusão: 3 g (1 col de sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Aplicar compressa na área a ser tratada de 2 a 3 x ao dia. \nExtrato\/tintura: 0, 16 a 0, 20 mg de lactonas sesquiterpênicas totais expressas em helenalina por g ou 0, 08 mg de\nlactonas sesquiterpênicas totais expressas em helenalina por ml.\r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Traumas, contusões, torções, edemas devido a fraturas e torções. Hematomas.\r\n",
        ContraInd: "Não utilizar por via oral, pois pode causar gastrenterites e distúrbios cardiovasculares, falta de ar e morte. Não aplicar em feridas abertas\r\n",
        Efeitos: "Pode, em casos isolados, provocar reações alérgicas na pele como vesiculação e necrose. Não utilizar por um período superior a 7 dias pois o uso prolongado pode provocar reações do tipo dermatite de contato (irritação da pele), formação de vesículas e eczemas\r\n",
        InfoAdic: "Evitar o uso em concentrações superiores às recomendadas.\r\n"
    },
    {
        ID: 10,
        Fitoterapicos: "Aroeira-da-praia\r\n",
        Nomebot: "Schinus terebinthifolia\r\n",
        PartUtilizada: "Casca do caule\r\n",
        FormUtilizacao: "Decocção: 1 g em 1L água\r\n",
        Posologia: "Decocção: Aplicar na região afetada 2 x ao dia, em compressas, banhos de assento.\r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Inflamação vaginal, leucorréia (corrimento vaginal), como hemostático, adstringente e cicatrizante.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 11,
        Fitoterapicos: "Assa-peixe\r\n",
        Nomebot: "Vernonia polyanthes\r\n",
        PartUtilizada: "Folha\r\n",
        FormUtilizacao: "Infusão: 3 g (1 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Oral: Gargarejar e, em seguida, ingerir 1 xícara (150 ml) 3 x\/dia.\nTópico: Aplicar sobre a área afetada 2 x dia durante 2 horas de cada vez.\r\n",
        Via: "Oral e Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Oral: Bronquite e tosse persistente. Tópico: Dores musculares\r\n",
        ContraInd: "Não deve ser utilizada durante a gravidez e lactação\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 12,
        Fitoterapicos: "Babosa ou Áloe\r\n",
        Nomebot: "Aloe Vera\r\n",
        PartUtilizada: "Gel Mucilaginoso das folhas\r\n",
        FormUtilizacao: "Extrato obtido do gel\r\n",
        Posologia: "Concentração da forma farmacêutica: 0,03 a 0,2 mg de polissacarídeos totais por 100 mg.\r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Cicatrizante nas lesões provocadas por queimaduras térmicas (1º e 2º graus) e radiação.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 13,
        Fitoterapicos: "Barbatimão\r\n",
        Nomebot: "Stryphnodendrom adstrigens\r\n",
        PartUtilizada: "Casca\r\n",
        FormUtilizacao: "Decocção: 3 g (col sopa) em 1 L de água\r\n",
        Posologia: "Decocção: Aplicar compressas no local afetado 2-3x ao dia.\r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Lesões como cicatrizante e anti-séptico tópico na pele e mucosas bucal e genital.\r\n",
        ContraInd: "Não deve ser utilizado em lesões com processo inflamatório intenso.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 14,
        Fitoterapicos: "Bardana\r\n",
        Nomebot: "Arctium lappa\r\n",
        PartUtilizada: "Raízes\r\n",
        FormUtilizacao: "Decocção: 2,5 g (2,5 col chá) em 150 ml (xíc chá)\r\n",
        Posologia: "Oral: Dispepsia (Distúrbios digestivos). Como diurético e como antiinflamatório nas dores articulares (artrite)\nTópico: Dermatites (irritação da pele), como anti-séptico e antiinflamatório.\r\n",
        Via: "Oral e Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Oral: Dispepsia (Distúrbios digestivos). Como diurético e como antiinflamatório nas dores articulares (artrite)\nTópico: Dermatites (irritação da pele), como anti-séptico e antiinflamatório.",
        ContraInd: "Não deve ser utilizado por período superior ao recomendado. Deverá ser utilizado com cautela na gravidez.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 15,
        Fitoterapicos: "Boldo-baiano\r\n",
        Nomebot: "Vernonia condensata\r\n",
        PartUtilizada: "Folha\r\n",
        FormUtilizacao: "Infusão: 3 g (1 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc, 3X dia, antes das principais refeições.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dor e dispepsia.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 16,
        Fitoterapicos: "Boldo-do-chile\r\n",
        Nomebot: "Peumus boldus\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 1 a 2 g (1 a 2 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá 2 x ao dia.\nExtratos\/tintura: 2 a 5 mg alcalóides totais expressos em boldina",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dispepsia (distúrbios da digestão), como colagogo e colerético, distrúrbios gastrointestinais espásticos.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas com obstrução das vias biliares, doenças severas no fígado e nos casos de gravidez. Usar cuidadosamente em pessoas com doença hepática aguda ou severa, colecistite séptica, espasmos do intestino e íleo e câncer hepático.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não exceder a dosagem recomendada\r\n"
    },
    {
        ID: 17,
        Fitoterapicos: "Boldo-nacional, Hortelã-homem, Falso-boldo  , Boldoafricano\r\n",
        Nomebot: "Plectranthus barbatus\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 1-3 g (1-3 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão:Utilizar 1 xíc chá de 2 a 3 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dispepsia (distúrbios da digestão) e hipotensão (pressão baixa).\r\n",
        ContraInd: "Não deve ser utilizado em gestantes, lactantes, crianças, pessoas com hipertensão (pressão alta), hepatites e obstrução das vias biliares. Pessoas que fazem uso de medicamentos para o sistema nervoso central devem evitar o uso.\r\n",
        Efeitos: "O uso pode diminuir a pressão arterial. Doses acima da recomendada e utilizadas por um período de tempo maior que o recomendado podem causar irritação gástrica.\r\n",
        InfoAdic: "Não usar junto com metronidazol ou dissulfiram.\r\n"
    },
    {
        ID: 18,
        Fitoterapicos: "Cajueiro\r\n",
        Nomebot: "Anacardium occidentale\r\n",
        PartUtilizada: "Entrecasca\r\n",
        FormUtilizacao: "Decocção: 4,5 g (1 ½ col sopa) em 150 ml (xíc chá)\r\n",
        Posologia: "Oral:  Utilizar 1 xíc, 3 a 4 x dia \nTópico: Aplicar compressa na região afetada 3 a 4 x dia.",
        Via: "Oral e Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Oral: Diarréia não infecciosa\nTópico: Lesões como anti-séptico e cicatrizante",
        ContraInd: "Não deve ser utilizado por periodo superior ao recomendado. Deverá ser utilizado com cautela na gravidez.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não utilizar junto com anticoagulantes, corticóides e antiinflamatórios\r\n"
    },
    {
        ID: 19,
        Fitoterapicos: "Calêndula\r\n",
        Nomebot: "Calendula officinalis\r\n",
        PartUtilizada: "Flores\r\n",
        FormUtilizacao: "Infusão: 1-2 g (1 a 2 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Aplicar compressa na área região afetada 3 x ao dia.\nExtrato\/ Tintura: 1,6 a 5 mg de flavonóides totais expressos em hiperosídeos por 100g ou 0,8 a 1,0 mg de flavonóides totais expressos em hiperosídeos por ml.\r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Inflamações e lesões, contusões e queimaduras. Cicatrizante, antiinflamatório.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 20,
        Fitoterapicos: "Camomila\r\n",
        Nomebot: "Matricaria recutita\r\n",
        PartUtilizada: "Flores, Capítulo floral\r\n",
        FormUtilizacao: "Oral: Infusão: 3g (1 col de sopa) em 150ml (xíc chá)\nTópico:Infusão: 6-9g (2-3 Col sopa) em 150 ml (xíc chá)\n",
        Posologia: "Oral: Utilizar 1 xíc chá de 3 a 4 x ao dia\nExtrato: 4 a 24 mg apigenina-7-glicosídeo\nTópico: Aplicar de 3 a 4 x ao dia, em forma de compressas, bochechos e gargarejos.\nTintura: 0,009 a 0,03 mg apigenina 7-glicosídeo por 100 mg ou 0,015.\r\n",
        Via: "Oral e Tópico\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Oral: Cólicas intestinais. Quadros leves de ansiedade, como calmante suave\nTópico: Contusões e dos processos inflamatórios da boca e gengiva.",
        ContraInd: "Insuficiência venosa dos membros inferiores.\r\n",
        Efeitos: "Oral: Podem ocorrer reações alérgicas ocasionais. Em caso de superdose, pode ocorrer o aparecimento de náuseas, excitação nervosa e insônia\r\n",
        InfoAdic: "Tópico: Não aplicar a infusão na região próxima aos olhos\r\n"
    },
    {
        ID: 21,
        Fitoterapicos: "Canela, Canela-do-Ceilão\r\n",
        Nomebot: "Cinnamomum verum\r\n",
        PartUtilizada: "Casca\r\n",
        FormUtilizacao: "Decocção: 0,5-2 g (1 a 4 col café) em 150 mL (xíc chá)\r\n",
        Posologia: "Decocção: Utilizar 1 xíc chá de 2 a 6 x ao dia\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Falta de apetite, perturbações digestivas com cólicas leves, flatulência (gases) e sensação de plenitude gástrica.\r\n",
        ContraInd: "Não utilizar na gravidez.\r\n",
        Efeitos: "Podem ocorrer reações alérgicas de pele e mucosas.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 22,
        Fitoterapicos: "Capim santo, Capim limão, Capim cidró, Capim cidreira, Cidreira\r\n",
        Nomebot: "Cymbopogon citratus\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 1-3g (1 a 3 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 2 a 3 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Cólicas intestinais e uterinas. Quadros leves de ansiedade e insônia, como calmante suave.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Pode aumentar o efeito de medicamentos sedativos (calmantes)\r\n"
    },
    {
        ID: 23,
        Fitoterapicos: "Caralluma\r\n",
        Nomebot: "Caralluma Fimbriata\r\n",
        PartUtilizada: "Flores, talos\r\n",
        FormUtilizacao: "Extra Seco\r\n",
        Posologia: "1 a 2 g dia, antes das refeições.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Tratamento para emagrecimento, diminui glicose no sangue e inibe apetite.\r\n",
        ContraInd: "Gestação e lactação\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 24,
        Fitoterapicos: "Cardo Mariano\r\n",
        Nomebot: "Silybum marianum\r\n",
        PartUtilizada: "Sementes\r\n",
        FormUtilizacao: "Extra Seco\r\n",
        Posologia: "180 a 540 mg ao dia\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Distúrbios digestivos que ocorrem nas hepatopatias e das lesões tóxicas do fígado, tratamento de suporte na doença inflamatória crônica do fígado e na cirrose hepática.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Leve efeito laxativo\r\n",
        InfoAdic: "Não utilizar em crianças menores de 12 anos, gestantes e lactantes.\r\n"
    },
    {
        ID: 25,
        Fitoterapicos: "Carqueja; Carqueja amarga\r\n",
        Nomebot: "Baccharis trimera\r\n",
        PartUtilizada: "Partes aéreas\r\n",
        FormUtilizacao: "Infusão: 2,5 g (2,5 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 2 a 3 x ao dia\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dispepsia (Distúrbios da digestão).\r\n",
        ContraInd: "Não utilizar em grávidas, pois pode promover contrações uterinas.Evitar o uso concomitante com medicamentos para hipertensão e diabetes.\r\n",
        Efeitos: "O uso pode causar hipotensão (queda da pressão)\r\n",
        InfoAdic: "O uso pode causar hipotensão (queda da pressão)\r\n"
    },
    {
        ID: 26,
        Fitoterapicos: "Cáscara sagrada\r\n",
        Nomebot: "Rhamnus purshiana\r\n",
        PartUtilizada: "Casca\r\n",
        FormUtilizacao: "Decocção: 0,5 g (col café) em 150 mL (xíc chá)\r\n",
        Posologia: "Decocção: Utilizar de ½ a 1 xíc chá, antes de dormir.\nExtrato\/ Tintura: 20 a 30 mg de cascarosídeo A.\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Constipação intestinal eventual. Efeito Laxativo.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas com obstrução intestinal refluxo, inflamação intestinal aguda (doença de Crohn), colite, apendicite ou dor abdominal de origem desconhecida, pacientes  com histórico de polipos e intestinal. Não utilizar durante lactação, gravidez e em menores de 12 anos.\r\n",
        Efeitos: "Pode ocorrer desconforto no trato gastrintestinal, principalmente em pacientes com cólon irritável, além de mudança de coloração na urina\r\n",
        InfoAdic: "Não fazer uso crônico (mais de 1 semana). O uso contínuo pode promover diarréia, perda de eletrólitos e  dependência\r\n"
    },
    {
        ID: 27,
        Fitoterapicos: "Castanha-da-índia\r\n",
        Nomebot: "Aesculus hippocastanum\r\n",
        PartUtilizada: "Sementes com casca\r\n",
        FormUtilizacao: "Infusão: 1,5 g (1 ½ col de chá) em 150 ml (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá, 2 x dia, logo após as refeições\nExtrato\/ Tintura: Dose diária de 32 a 120 mg de escina",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Fragilidade capilar, insuficiência venosa (hemorróidas e varizes).\r\n",
        ContraInd: "Não utilizar na gravidez, lactação, insuficiência hepática e renal, como também em casos de lesões da mucosa digestiva em atividade.\r\n",
        Efeitos: "Altas doses podem causar irritação do trato digestivo, náusea e vômito\r\n",
        InfoAdic: "Não utilizar junto com anticoagulantes\r\n"
    },
    {
        ID: 28,
        Fitoterapicos: "Catuaba\r\n",
        Nomebot: "Trichilia catigua\r\n",
        PartUtilizada: "Casca\r\n",
        FormUtilizacao: "Extrato seco\r\n",
        Posologia: "400 mg 3x ao dia\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Afrodidíaco e estimulante do sistema nervoso central. Impotência, agitação, nervosismo, nevralgia e cansaço, problemas de memória e fraqueza sexual.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 29,
        Fitoterapicos: "Cavalinha\r\n",
        Nomebot: "Equisetum arvense\r\n",
        PartUtilizada: "Partes aéreas\r\n",
        FormUtilizacao: "Infusão: 3 g (1 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá 2 a 4 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Edemas (inchaços) por retenção de líquidos.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas com insuficiência renal e cardíaca.\r\n",
        Efeitos: "Não deve ser utilizado por pessoas com insuficiência renal e cardíaca.\r\n",
        InfoAdic: "Uma alergia rara pode ocorrer em pacientes sensíveis à nicotina. O uso por período superior ao recomendando pode provocar dor de cabeça e  anorexia.Altas doses podem provocar irritação gástrica, reduzir os níveis de vitamina B1 e provocar irritação no sistema urinário\r\n"
    },
    {
        ID: 30,
        Fitoterapicos: "Centela, Centela-asiática\r\n",
        Nomebot: "Centella asiatica\r\n",
        PartUtilizada: "Partes aéreas\r\n",
        FormUtilizacao: "Extratos\r\n",
        Posologia: "Dose Diária: 6,6 a 13,6 mg de derivados triterpênicos totais expressos em asiaticosídeo.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Insuficiência venosa dos membros inferiores.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 31,
        Fitoterapicos: "Chá Verde\r\n",
        Nomebot: "Camellia sinensis\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Extrato seco\/ Pó\r\n",
        Posologia: "Extrato seco(5%): 50-100 mg ao dia, preferencialmente pela manhã.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Redução do colesterol e triglicérides; redução da agregação plaquetária no sangue; melhoria das atividades do sistema imunológico e aumenta a perda de peso.\r\n",
        ContraInd: "Pacientes em uso de anticoagulante, gravidez e lactação.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Pode afetar a absorção dos seguintes medicamentos: Atropina, Codeína, Efedrina, Pseudoefebrina,Teofilina, Aminofilina e Haloperidol.\r\n"
    },
    {
        ID: 32,
        Fitoterapicos: "Chambá, Chachambá, Trevo-cumaru\r\n",
        Nomebot: "Justicia pectoralis\r\n",
        PartUtilizada: "Partes aéreas\r\n",
        FormUtilizacao: "Infusão: 5 g (5 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 2 a 3 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n ",
        Ind: "Tosse, como expectorante e broncodilatador.\r\n",
        ContraInd: "Pacientes com problemas de coagulação e em uso de anticoagulantes e analgésicos.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 33,
        Fitoterapicos: "Chapéu de couro\r\n",
        Nomebot: "Echinodorus macrophyllus\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 1 g (1 col chá) em 150 mL (xíc de chá) \r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá 3 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Edemas (inchaço) por retenção de líquidos e processos inflamatórios.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas portadores de insuficiência renal e cardíaca.\r\n",
        Efeitos: "Não utilizar doses acima da recomendada pois pode causa diarréia\r\n",
        InfoAdic: "Pode interagir com medicamentos anti-hipertensivos, causando queda da pressão\r\n"
    },
    {
        ID: 34,
        Fitoterapicos: "Cimicífuga\r\n",
        Nomebot: "Cimicifuga racemosa\r\n",
        PartUtilizada: "Raiz ou Rizoma\r\n",
        FormUtilizacao: "Extratos\r\n",
        Posologia: "Dose Diária: 2 a 7 mg de glicosídeos triterpênicos expressos em 26-deoxiacteína.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Sintomas do climatério.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Restrito à Prescrição.\r\n"
    },
    {
        ID: 35,
        Fitoterapicos: "Confrei\r\n",
        Nomebot: "Symphytum Officinale\r\n",
        PartUtilizada: "Raízes\r\n",
        FormUtilizacao: "Extratos\r\n",
        Posologia: "Concentração da forma farmacêutica: 0,03 a 0,16 mg de alantoína por 100 mg.\r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Cicatrizante, equimoses, hematomas e contusões.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Utilizar por no máximo 4-6 semanas\/ano, somente em lesões localizadas, quando abertas.\r\n"
    },
    {
        ID: 36,
        Fitoterapicos: "Curcuma, Açafroa, Açafrão da Terra\r\n",
        Nomebot: "Curcuma longa\r\n",
        PartUtilizada: "Rizomas\r\n",
        FormUtilizacao: "Decocção: 1,5 g (3 col café) em 150 mL água (xíc chá).\r\n",
        Posologia: "Decocção: Utilizar 1 xic chá 1 a 2 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Dispepsia (distúrbios digestivos). Como antiiinflamatório.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas portadoras de obstrução dos dutos biliares e em caso de úlcera gastroduodenal. Em caso de cálculos biliares (pedra na vesícula), utilizar somente sob avaliação médica.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não utilizar junto com anticoagulantes\r\n"
    },
    {
        ID: 37,
        Fitoterapicos: "Dente de leão\r\n",
        Nomebot: "Taraxacum officinale\r\n",
        PartUtilizada: "Toda a planta\r\n",
        FormUtilizacao: "Decocção: 3-4 g (3- 4 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Decocção: Utilizar 1 xíc chá 3 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dispepsia (distúrbios digestivos), estimulante do apetite e como diurético.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas portadoras de obstrução dos dutos biliares e do trato intestinal. Na ocorrência de cálculos biliares, consultar profissional de saúde antes do uso.\r\n",
        Efeitos: "O uso pode provocar hiperacidez gástrica e hipotensão (queda da pressão)\r\n",
        InfoAdic: "Não utilizar em menores de dois anos\r\n"
    },
    {
        ID: 38,
        Fitoterapicos: "Equinácea\r\n",
        Nomebot: "Echinacea purpurea Moench\r\n",
        PartUtilizada: "Partes aéreas floridas\r\n",
        FormUtilizacao: "Extratos\r\n",
        Posologia: "Dose Diária: 13 a 36 mg de fenóis totais expressos em ácido caftárico, ácido chicórico, ácido clorogênico e equinacosídeo.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Preventivo e coadjuvante na terapia de resfriados e infecções do trato respiratório e urinário.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Restrito à Prescrição Médica\r\n"
    },
    {
        ID: 39,
        Fitoterapicos: "Erva-baleeira\r\n",
        Nomebot: "Cordia verbenacea\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 3 g (1 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Oral: Utilizar 1 xíc, 3 x dia\nInterno: Aplicar compressa na região afetada 3 x dia.\r\n",
        Via: "Oral e Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Inflamação em contusões e dor.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 40,
        Fitoterapicos: "Erva-cidreira, Falsa erva- cidreira, Falsamelissa\r\n",
        Nomebot: "Lippia alba\r\n",
        PartUtilizada: "Partes aéreas\r\n",
        FormUtilizacao: "Infusão: 1 a 3 g (1 a 3 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 3 a 4 x ao dia. \r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Quadros leves de ansiedade e insônia, como calmante suave.\r\n",
        ContraInd: "Uso cuidadosamente em pessoas com hipotensão (pressão baixa).\r\n",
        Efeitos: "Doses acima da recomendada podem causar irritação gástrica, bradicardia (diminuição da freqüência cardíaca) e hipotensão (queda da pressão)\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 41,
        Fitoterapicos: "Erva-de- bicho, Pimenteira-dágua\r\n",
        Nomebot: "Polygonum punctatum\r\n",
        PartUtilizada: "Partes aéreas\r\n",
        FormUtilizacao: "Infusão: 3 g (1 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Aplicar na região afetada 3 x dia.\r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Varizes e úlceras varicosas.\r\n",
        ContraInd: "Gravidez\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 42,
        Fitoterapicos: "Espinheira santa\r\n",
        Nomebot: "Maytenus ilicifolia\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 1-2 g (1-2 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: 1-2 g (1-2 col chá) em 150 mL (xíc chá)\nExtratos\/tintura: 60 a 90 mg taninos totais.",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dispepsia (distúrbios da digestão), azia e gastrite.Coadjuvante no tratamento episódico de prevenção de úlcera em uso de antiinflamatórios não esteroidais.\r\n",
        ContraInd: "Não deve ser utilizado por crianças menores de 6 anos. Não utilizar em grávidas até o terceiro mês de gestação e lactantes, pois promove a redução do leite.\r\n",
        Efeitos: "O uso pode provocar secura, gosto estranho na boca e náuseas\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 43,
        Fitoterapicos: "Eucalipto\r",
        Nomebot: "Eucalyptus globulus\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 2 g (col sobremesa) em 150 mL (xíc chá)\r\n",
        Posologia: "Inalatório: Fazer inalação de 2 a 3 x ao dia.\nOral: Óleo essencial\/extratos\/tintura: 14 a 42,5 mg de cineol.\r\n",
        Via: "Oral e Inalatório\r\n",
        Uso: "Adulto\r\n",
        Ind: "Gripes e resfriados para desobstrução das vias respiratórias, como adjuvante no tratamento de bronquite e asma. Anti-séptico e antibacteriano das vias aéreas superiores, expectorante.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas com inflamação gastrointestinal e biliar, doença hepática grave, gravidez, lactação e em menores de 12 anos.\r\n",
        Efeitos: "Em casos raros, pode provocar náusea, vômito e diarréia\r\n",
        InfoAdic: "Evitar o uso associado com sedativos, anestésicos e analgésicos, pois  Pode potencializar suas ações. Pode interferir com tratamentos hipoglicemiantes. Colocar a infusão em recipiente aberto, cobrir a cabeça com um pano junto ao recipiente e inalar\r\n"
    },
    {
        ID: 44,
        Fitoterapicos: "Fucus, alface do mar, cavalo marinho, alga vesiculosa\r\n",
        Nomebot: "Fucus vesiculosus\r\n",
        PartUtilizada: "Alga inteira, talo \r\n",
        FormUtilizacao: "Extrato seco\/ Pó\r\n",
        Posologia: "Extrato Seco: 0,3 a 1g\/dia.\nPó: 0,5 a 2 gramas, uma a três vezes ao dia.",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Tratamento de hipotireoidismo e disfunções da tireoide devido à grande concentração de iodo, favore processos catabólicos, regulaçãos dos hormonios tireoidianos. A algina presente na alga atua como protetor das mucosas digestivas. Os sais de potássio promovem ligeira ação  diurética. O alginato de cálcio pode ser usado como um hemostático local de ação rápida. A laminarina exerce uma ação hipocolesterolemiante.\r\n",
        ContraInd: "Não utilizar em pacientes que fazem tratamento com hormônios tireoidianos.\r\n",
        Efeitos: "Uso prolongado pode ocasionar intoxicação por iodo.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 45,
        Fitoterapicos: "Garcinia\r\n",
        Nomebot: "Garcinia cambogia\r\n",
        PartUtilizada: "Fruto\r\n",
        FormUtilizacao: "Extrato seco\r\n",
        Posologia: "1 a 3 g divididas em cápsulas de 300-450 mg, antes das refeições principais.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Coadjuvante no tratamento de emagrecimento.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 46,
        Fitoterapicos: "Garra do diabo\r\n",
        Nomebot: "Harpagophytum procumbens\r\n",
        PartUtilizada: "Raiz\r\n",
        FormUtilizacao: "Infusão: 1 g (1 colher de chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc, 2 a 3 X dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dores articulares (Artrite, artrose, artralgia).\r\n",
        ContraInd: "Não utilizar em portadores de úlceras estomacais e duodenais.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 47,
        Fitoterapicos: "Gengibre\r\n",
        Nomebot: "Zingiber officinale\r\n",
        PartUtilizada: "Rizomas\r\n",
        FormUtilizacao: "Decocção: 0,5 - 1 g (1 a 2 col café) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 2 a 4x ao dia.\nExtratos: Crianças acima de 6 anos: 4 a 16 mg de gingeróis; adulto: 16 a 32 mg de gingeróis.",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Profilaxia de enjôos, náuseas e vômitos: de gestação, de movimento (cinetose) e pós-operatório. Dispepsias em geral.\r\n",
        ContraInd: "Em casos de cálculos biliares, utilizar apenas com acompanhamento de  profissional de saúde. Evitar o uso em paciente s que estejam usando  anticoagulantes, com desordens de coagulação, ou com cálculos biliares; irritação gástrica e hipertensão, especialmente em doses altas. Evitar o uso em menores de seis anos.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 48,
        Fitoterapicos: "Ginkgo\r\n",
        Nomebot: "Ginkgo biloba\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Extratos\r\n",
        Posologia: "Dose Diária: 26,4 a 64,8 mg de ginkgoflavonóides e 6 a 16,8 mg de terpenolactonas.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Vertigens e zumbidos (tinidos) resultantes de distúrbios circulatórios, distúrbios circulatórios periféricos (claudicação intermitente), insuficiência vascular cerebral.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Restrito à Prescrição Médica\r\n"
    },
    {
        ID: 49,
        Fitoterapicos: "Ginseng\r\n",
        Nomebot: "Panax ginseng\r\n",
        PartUtilizada: "Raiz\r\n",
        FormUtilizacao: "Extratos\/tintura\r\n",
        Posologia: "Dose Diária: 5 a 30 mg de ginsenosídeos toais (Rb1, Rg1).\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n ",
        Ind: "Estado de fadiga física e mental, adaptógeno.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Utilizar por no máximo três meses\r\n"
    },
    {
        ID: 50,
        Fitoterapicos: "Goiabeira\r\n",
        Nomebot: "Psidium guajava\r\n ",
        PartUtilizada: "Folhas Jovens\r\n",
        FormUtilizacao: "Infusão: 2 g (col sobremesa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 cálice (30 ml) após a evacuação em no máximo 10 x ao dia.\r\n",
        Via: "Oral e Tópico\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Oral: Diarréias não infecciosas.\nTópico: Pele e mucosas lesadas, como anti-séptico.",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não utilizar continuamente\r\n"
    },
    {
        ID: 51,
        Fitoterapicos: "Guaçatonga, Erva-de-bugre, Erva-de-lagarto\r\n",
        Nomebot: "Casearia sylvestris\r\n",
        PartUtilizada: "Folha\r\n",
        FormUtilizacao: "Infusão: 2 a 4 g (1 a 2 col de sobremesa) em 150 ml (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá 3-4 x ao dia\r\n",
        Via: "Tópico e Interno\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Oral: Dor e lesões, como antiséptico e cicatrizante tópico.\nInterno: Dispepsia (distúrbios digestivos), gastrite e halitose (mal hálito).",
        ContraInd: "Não utilizar na gravidez e lactação.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 52,
        Fitoterapicos: "Guaco\r\n",
        Nomebot: "Mikania glomerata\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 3 g (1 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá 3 x ao dia\nExtrato\/tintura: 0,5 a 5 mg de cumarina",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Gripes e resfriados, bronquites  alérgica e infecciosa, como expectorante e broncodilatador.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "A utilização pode interferir na coagulação sanguínea. Doses acima da recomendada podem provocar vômitos e diarréia;\r\n",
        InfoAdic: "Pode interagir com antiinflamatórios não-esteroidais\r\n"
    },
    {
        ID: 53,
        Fitoterapicos: "Guaraná\r\n",
        Nomebot: "Paullinia cupana\r\n",
        PartUtilizada: "Sementes\r\n",
        FormUtilizacao: "0,5-2 g do pó (1 a 4 col café)\r\n",
        Posologia: "Utilizar puro ou diluído em água.\nExtrato\/tintura: 15 a 70 mg de trimetilxantina (cafeína).",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Fadiga como estimulante.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas com ansiedade, hipertiroidismo, hipertensão, arritmias, problemas cardíacos, estomacais e intestinais, taquicardia paroxística, gastrite e cólon irritável.\r\n",
        Efeitos: "Em altas doses pode causar insônia, nervosismos e ansiedade.\r\n",
        InfoAdic: "Não associar com outras drogas com bases xânticas (café, noz de cola, mate), nem com anti-hipertensivos\r\n"
    },
    {
        ID: 54,
        Fitoterapicos: "Hamamélis\r\n",
        Nomebot: "Hamamelis virginiana\r\n",
        PartUtilizada: "Cascas e folhas \r\n",
        FormUtilizacao: "Deccocção: 3-6 g (1- 2 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Aplicar em compressas na região afetada 2 a 3 x ao dia.\nExtrato\/Tintura: 0,35 a 1 mg de taninos por 100 mg ou 3,5 a 10 mg de taninos por ml.\r\n",
        Via: "Tópico e Interno\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Tópico: Inflamações da pele e mucosas, hemorróidas externas, equimoses.\nInterno: Hemorróidas",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não ingerir, pois pode, eventualmente, provocar irritação gástrica e vômitos\r\n",
        InfoAdic: "Nunca usar continuamente por mais de 4 semanas\r\n"
    },
    {
        ID: 55,
        Fitoterapicos: "Hipérico\r\n",
        Nomebot: "Hypericum perforatum\r\n",
        PartUtilizada: "Partes aéreas\r\n",
        FormUtilizacao: "Extratos\/tintura\r\n",
        Posologia: "Dose Diária: 0,9 a 2,7 mg hipericinas totais expressas em hipericina.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Estados depressivos leves a moderados.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Restrito à Prescrição Médica\r\n"
    },
    {
        ID: 56,
        Fitoterapicos: "Hortelã-pimenta\r\n",
        Nomebot: "Mentha piperita\r\n",
        PartUtilizada: "Folhas e sumidades floridas\r\n",
        FormUtilizacao: "Infusão: 1,5 g (3 col café) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 2 a 4 x ao dia.\nÓleo essencial: 60 a 440 mg de mento e 28 a 256 mg de mentona.",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Cólicas, flatulência (gases), problemas hepáticos, carminativo, antiespasmódico intestinal, expectorante.\r\n",
        ContraInd: "Não deve ser utilizado em casos de obstruções biliares, danos hepáticos severos e durante a lactação. Na presença de cálculos biliares, consultar  profissional de saúde antes de usar.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 57,
        Fitoterapicos: "Jucá, Pau-ferro\r\n",
        Nomebot: "Caesalpinia ferrea\r\n",
        PartUtilizada: "Favas\r\n",
        FormUtilizacao: "Decocção: 7,5 g (2,5 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Decocção: Aplicar compressa na região afetada de 2 a 3 x ao dia \r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Lesões, como adstringente, hemostático, cicatrizante e anti-séptico.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 58,
        Fitoterapicos: "Jurubeba\r\n",
        Nomebot: "Solanum paniculatum\r\n",
        PartUtilizada: "Planta inteira\r\n",
        FormUtilizacao: "Infusão: 1 g (1 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 3 a 4 x ao dia.'\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dispepsia (distúrbios da digestão).\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Doses acima da recomendada e por período de tempo acima do recomendado podem causar intoxicação com náuseas, vômitos,  diarréia, cólicas abdominais, confusão mental, edema cerebral e morte\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 59,
        Fitoterapicos: "Kava kava\r\n",
        Nomebot: "Piper methysticum\r\n",
        PartUtilizada: "Rizomas\r\n",
        FormUtilizacao: "Extratos\/tintura\r\n",
        Posologia: "Dose diária: 60 a 210 mg de kavapironas. \r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Ansiolítico\/ansiedade e insônia.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Utilizar no máximo por dois meses. Restrito à Prescrição Médica. \r\n"
    },
    {
        ID: 60,
        Fitoterapicos: "Laranja-amarga\r\n",
        Nomebot: "Citrus aurantium\r\n",
        PartUtilizada: "Flores\r\n",
        FormUtilizacao: "Maceração: 1-2 g (1-2 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Maceração: Utilizar 1 a 2 xíc chá, antes de dormir.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Quadros leves de ansiedade e insônia, como calmante suave.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas portadoras de distúrbios cardíacos.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Respeitar rigorosamente as doses recomendadas. Deixar em maceração por 3 a 4 horas\r\n"
    },
    {
        ID: 61,
        Fitoterapicos: "Macela; Marcela;Marcela do campo\r\n",
        Nomebot: "Achyrocline satureioides\r\n",
        PartUtilizada: "Sumidades floridas\r\n",
        FormUtilizacao: "Infusão: 1-2 g (1-2 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá 4 x ao  dia\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Má digestão e cólicas intestinais; como sedativo leve; e como antiinflamatório.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 62,
        Fitoterapicos: "Malva\r\n",
        Nomebot: "Malva sylvestris\r\n",
        PartUtilizada: "Folhas e flores\r\n",
        FormUtilizacao: "Oral: Infusão: Infusão: 2-3 g (2-3 col chá) em 150 mL (xíc chá)\nTópico:Infusão: 6-9g (2-3 Col sopa) em 150 ml (xíc chá)\n",
        Posologia: "Oral: Utilizar 1 xíc chá 4 x ao dia\nTópico: Aplicar de 3 a 4 x ao dia.",
        Via: "Oral e Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Oral: Afecções respiratórias como expectorante.\nTópico: Contusões e dos processos inflamatórios da boca e garganta.\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 63,
        Fitoterapicos: "Maracujá, Passiflora\r\n",
        Nomebot: "Passiflora alata\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 3 g (1 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 1 a 2 x ao dia.\nExtrato\/tintura: 20 a 64 mg de flavonóides totais expressos em vitexina.\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Quadros leves de ansiedade e insônia, como calmante suave, ansiolítico leve.\r\n",
        ContraInd: "Não constam.\r\n ",
        Efeitos: "O uso pode causar sonolência\r\n",
        InfoAdic: "Não deve ser usado junto com medicamentos  sedativos e depressores do sistema  nervoso.Nunca utilizar cronicamente.\r\n"
    },
    {
        ID: 64,
        Fitoterapicos: "Melão-de-São-Caetano\r\n",
        Nomebot: "Momordica charantia\r\n",
        PartUtilizada: "Folhas, frutos e sementes\r\n",
        FormUtilizacao: "Deccocção: 5g em 1L\r\n",
        Posologia: "Deccocção: Aplicar nos locais afetados 2 x dia ou banhar-se uma vez ao dia.\r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dermatites (irritação da pele) e escabiose (sarna).\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Pode interagir com hipoglicemiantes. Não utilizar por via oral, pois pode causar coma hipoglicêmico (por diminuição de açúcar  no sangue) e convulsões em crianças;  problemas hepáticos e dor de cabeça\r\n"
    },
    {
        ID: 65,
        Fitoterapicos: "Melissa, Erva-cidreira\r\n",
        Nomebot: "Melissa officinalis\r\n",
        PartUtilizada: "Sumidades floridas, folhas\r\n",
        FormUtilizacao: "Infusão: 2 a 4g (1-2 col sobremesa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 2 a 3 x ao dia.\nExtratos\/Tintura: 60 a 180 mg de ácidos hidroxicinâmicos expressos em ácido rosmarínico.",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Cólicas abdominais. Quadros leves de ansiedade e insônia, como calmante suave, antiespasmódico, carminativo.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas com hipotiroidismo (redução da função da tireóide).\r\n",
        Efeitos: "Utilizar cuidadosamente em pessoas com pressão baixa\r\n ",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 66,
        Fitoterapicos: "Mentrasto, Catinga de bode\r\n",
        Nomebot: "Ageratum conyzoides\r\n",
        PartUtilizada: "Partes aéreas sem as flores\r\n",
        FormUtilizacao: "Infusão: 2-3 g (2-3 col chá) em 150 mL (xíc de chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 2 a 3 x ao dia\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dores articulares (Artrite, artrose) e reumatismo.\r\n",
        ContraInd: "Não deve ser utilizado por  pessoas com problemas hepáticos.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Nunca usar por mais de três semanas consecutivas.\r\n"
    },
    {
        ID: 67,
        Fitoterapicos: "Mil folhas\r\n",
        Nomebot: "Achillea millefolium\r\n",
        PartUtilizada: "Partes aéreas \r\n",
        FormUtilizacao: "Infusão: 1-2 g (1-2 col chá) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 3 a 4 x ao dia\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Falta de apetite, dispepsia (perturbações digestivas), febre, inflamação e cólicas.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas portadoras de úlcera gástrica ou duodenal ou com oclusão das vias biliares.\r\n",
        Efeitos: "O uso pode causar cefaléia e inflamação. O uso prolongado pode provocar reações alérgicas. Caso ocorra, um desses sintomas, suspender o uso e consultar um especialista\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 68,
        Fitoterapicos: "Mulungu\r\n",
        Nomebot: "Erythrina verna\r\n",
        PartUtilizada: "Casca\r\n",
        FormUtilizacao: "Deccocção: 4 a 6 g  (2 a 3 col de sobremesa) em 150 ml (xíc chá)\r\n",
        Posologia: "Deccocção: Utilizar 1 xíc chá de 2 a 3 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Quadros leves de ansiedade e insônia, como calmante suave.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não usar por mais de 3 dias seguidos\r\n"
    },
    {
        ID: 69,
        Fitoterapicos: "Pata de Vaca\r\n",
        Nomebot: "Bauhinia forficata\r\n ",
        PartUtilizada: "Folha, casca dos ramos e flor\r\n",
        FormUtilizacao: "Infusão a 2% \/ Pó\r\n",
        Posologia: "Infusão a 2%: Até 6 xícaras de chá ao dia.\nPó:  2 a 3 cápsulas de 500mg dia.",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Diabetes, elefantíase.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 70,
        Fitoterapicos: "Pfaffia, paratudo, ginseng brasileiro\r\n",
        Nomebot: "Pfaffia paniculata\r\n",
        PartUtilizada: "Raiz\r\n",
        FormUtilizacao: "Pó ou concentração usual em cremes.\r\n",
        Posologia: "Interno: Pó: 5 a 10 g\/dia\nTópico: Concentrações usuais de 2 a 5% em cremes, loções e géis.\n\n",
        Via: "Interno\/Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Interno: Auxilar no tratamento de irregularidades circulatórias, estresse, anemia, diabetes e astenia. Estimula e tonifica o organismo, eliminando fadiga física e mental.\nTópico: Ação cicatrizante e regeneradora celular.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Superdosagem poda causar nervosismo, hipertensão, erupções na pele, diarreia e insônia.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 71,
        Fitoterapicos: "Picão\r\n",
        Nomebot: "Bidens pilosa\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 2 g (1 col sobremesa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá 4 x ao dia\r\n",
        Via: "Oral\r\n",
        Uso: "Infantil\r\n",
        Ind: "Icterícia (coloração amarelada de pele e mucosas devido a uma acumulação de bilirrubina no organismo).\r\n",
        ContraInd: "Não utilizar na gravidez.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 72,
        Fitoterapicos: "Pitangueira\r\n",
        Nomebot: "Eugenia uniflora\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 3 g (1 colher de sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 cálice (30 ml) após a evacuação em no máximo 10 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Diarréia não infecciosa\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 73,
        Fitoterapicos: "Poejo\r\n",
        Nomebot: "Mentha pulegium\r\n",
        PartUtilizada: "Partes aéreas\r\n",
        FormUtilizacao: "Infusão: 1 g (1 col sobremesa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 2 a 3 x ao dia durante ou após refeições.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Afecções respiratórias como expectorante. Estimulante do apetite perturbações digestivas, espasmos gastrointestinais, cálculos biliares e colecistite.\r\n",
        ContraInd: "Não deve ser utilizada na  gravidez, lactação e em crianças menores de 6 anos.  Contraindica-se o uso prolongado e a inalação.\r\n",
        Efeitos: "A administração em  doses e tempo de uso acima dos recomendados pode  promover danos no fígado e ocasionar problemas na gravidez\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 74,
        Fitoterapicos: "Polígala\r\n",
        Nomebot: "Polygala senega\r\n",
        PartUtilizada: "Raiz\r\n",
        FormUtilizacao: "Infusão: 4,5 g (1 ½ colher de sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá, 3 a 4 X dia.\nExtratos\/tintura: 18 a 33 mg de saponinas triterpênicas.",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Congestão respiratória, como expectorante.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Altas doses produzem efeito emetizante (provoca vômito) e diarréias, além de problemas gastrintestinais\r\n",
        InfoAdic: "Não constam.\r\n"
    },
    {
        ID: 75,
        Fitoterapicos: "Quebra-pedra\r\n",
        Nomebot: "Phyllanthus niruri\r\n",
        PartUtilizada: "Partes aéreas\r\n",
        FormUtilizacao: "Infusão: 3 g (1 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 2 a 3 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Litíase renal (cálculos renais) por auxiliar na eliminação de cálculos renais pequenos.\r\n",
        ContraInd: "Contra indicado na eliminação de cálculos grandes. Não utilizar na gravidez.\r\n",
        Efeitos: "Em concentrações acima da recomendada pode apresentar diarréia e hipotensão (pressão baixa)\r\n",
        InfoAdic: "Nunca utilizar por mais de 3 semanas\r\n"
    },
    {
        ID: 76,
        Fitoterapicos: "Romã\r\n",
        Nomebot: "Punica granatum\r\n",
        PartUtilizada: "Pericarpo (casca do fruto)\r\n",
        FormUtilizacao: "Decocção: 6 g (2 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Decocção: Aplicar no local afetado, em bochechos e gargarejos 3x dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Inflamações e infecções da mucosa da boca e faringe como antiinflamatório e anti-séptico.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Se ingerido, pode provocar zumbido, distúrbios visuais, espasmos na panturrilha e tremores.\r\n",
        InfoAdic: "Não engolir a preparação  após o bochecho e gargarejo\r\n"
    },
    {
        ID: 77,
        Fitoterapicos: "Sabugueiro\r\n",
        Nomebot: "Sambucus nigra\r\n",
        PartUtilizada: "Flor\r\n",
        FormUtilizacao: "Infusão: Utilizar 1 xíc, 2 a 3 X dia.\r\n",
        Posologia: "Extratos\/tintura: 80 a 120 mg de flanonóides totais expressos em isoquercitrina.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Tratamento sintomático de gripe e resfriado, mucolítico\/expecorante.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "O uso em quantidades maiores que o recomendado pode promover hipocalemia (diminuição da taxa de potássio no organismo)\r\n",
        InfoAdic: "Não utilizar folhas por conterem glicosídeos cianogênicos que podem ser toxicos.\r\n"
    },
    {
        ID: 78,
        Fitoterapicos: "Salgueiro, Salgueiro Branco\r\n",
        Nomebot: "Salix alba\r\n",
        PartUtilizada: "Casca do caule\r\n",
        FormUtilizacao: "Infusão: 3 g (1 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Utilizar 1 xíc chá de 2 a 3 x ao dia.\nExtratos: 60 a 120 mg de salicina.",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Inflamação, dor e febre. Gripe e resfriados. Antitérmico, antiinflamatório, analgésico.\r\n",
        ContraInd: "Não utilizar junto com Maracujá e Noz moscada.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Usar cautelosamente junto a anticoagulantes, corticóides e antiinflamatórios não esteroidais\r\n"
    },
    {
        ID: 79,
        Fitoterapicos: "Sálvia\r\n",
        Nomebot: "Salvia officinalis\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Oral: Infusão: 1,5-2 g (3 - 4 col café) em 150 mL (xíc chá)\nTópico: Infusão: 3,5 g (7 col café) em 150 mL (xíc chá)\r\n",
        Posologia: "Oral: Utilizar 1 xíc chá de 2 a 3 x ao dia.\nTópico: Aplicar no local afetado, em bochechos e gargarejos 1 ou 2 x dia",
        Via: "Oral e Tópico\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Oral: Dispepsias (distúrbios digestivos) e transpiração excessiva.\nTópico: Inflamações da boca e garganta, gengivites e aftas.",
        ContraInd: "Não utilizar na gravidez e lactação, insuficiência renal e tumores mamários  estrógeno dependentes.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não engolir a preparação após o bochecho e gargarejo pois pode causar náusea,  vômitos, dor abdominal, tonturas e  agitação. Pode elevar a pressão em pacientes hipertensos. Em altas doses pode ser neurotóxica (causar convulsões) e hepatotóxica (causar dano  no fígado)\r\n"
    },
    {
        ID: 80,
        Fitoterapicos: "Saw Palmetto\r\n",
        Nomebot: "Serenoa repens\r\n",
        PartUtilizada: "Frutos\r\n",
        FormUtilizacao: "Extrato\r\n",
        Posologia: "Dose Diária: 272 a 304 mg de ácidos graxos\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Hiperplasia benigna de próstata e sintomas associados.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Restrito à Prescrição Médica\r\n"
    },
    {
        ID: 81,
        Fitoterapicos: "Sene\r\n",
        Nomebot: "Senna alexandrina, Cassia angustifólia ou Cássia senna\r\n",
        PartUtilizada: "Frutos e folíolos\r\n",
        FormUtilizacao: "Decocção: 1 g (col café) em 150 mL (xíc chá)\r\n",
        Posologia: "Decocção: Utilizar de 1 xíc chá, antes de dormir.\nExtratos\/tinturas: 10 a 30 mg de derivados hidroxiantracênicos expressos em senosídeo B.",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Constipação intestinal eventual. Efeito Laxativo.\r\n",
        ContraInd: "Não deve ser utilizado por pessoas portadoras de obstrução intestinal, inflamação intestinal aguda (doença de  Crohn), colite, apendicite ou dor abdominal de origem não diagnosticada, constipação crônica. Não usar em crianças menores de 10 anos constipação crônica.\r\n",
        Efeitos: "Desconforto do trato gastrointestinal, principalmente em  pacientes com cólon irritável, mudança na coloração da urina\r\n",
        InfoAdic: "Não fazer uso crônico (mais de 1 semana). O uso contínuo pode promover diarréia e perda de eletrólitos\r\n"
    },
    {
        ID: 82,
        Fitoterapicos: "Tanaceto\r\n",
        Nomebot: "Tanacetum parthenium\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Extratos\/tintura\r\n",
        Posologia: "Dose Diária: 0,2 a 0,6 mg de partenolídeos.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Profilaxia de enxaqueca\r\n",
        ContraInd: "Não utilizar de forma contínua.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Restrito à Prescrição Médica\r\n"
    },
    {
        ID: 83,
        Fitoterapicos: "Tanchagem; Tansagem, Tranchagem\r\n",
        Nomebot: "Plantago major\r\n",
        PartUtilizada: "Folhas\r\n",
        FormUtilizacao: "Infusão: 6-9 g (2-3 col sopa) em 150 mL (xíc chá)\r\n",
        Posologia: "Infusão: Aplicar no local afetado, em bochechos e gargarejos 3x dia.\r\n",
        Via: "Tópico\r\n",
        Uso: "Adulto\r\n",
        Ind: "Inflamações da boca e faringe.\r\n",
        ContraInd: "Hipotensão arterial (pressão baixa), obstrução intestinal e gravidez.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não engolir a preparação após o bochecho e gargarejo. Nunca utilizar a casca da semente\r\n"
    },
    {
        ID: 84,
        Fitoterapicos: "Unha-de-gato\r\n",
        Nomebot: "Uncaria tomentosa\r\n",
        PartUtilizada: "Entrecasca\r\n",
        FormUtilizacao: "Decocção: 0,5 g (1 col café) em 150 mL (xíc chá)\r\n",
        Posologia: "Decocção: Utilizar 1 xíc chá de 2 a 3 x ao dia.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Dores articulares (artrite e artrose) e musculares agudas, como antiinflamatório.\r\n",
        ContraInd: "Não é recomendado o uso antes e depois de quimioterapia, nem em pacientes  hemofílicos. Não utilizar em menores de 3 anos.\r\n",
        Efeitos: "O uso pode provocar cansaço, febre, diarréia, constipação. Altas doses podem causar sintomas pancreáticos e alterações do nervo óptico.\r\n",
        InfoAdic: "Evitar o uso concomitante com imunossupressores e em pacientes transplantados ou esperando transplantes\r\n"
    },
    {
        ID: 85,
        Fitoterapicos: "Uva-Ursi\r\n",
        Nomebot: "Arctostaphylos uva-ursi Spreng\r\n",
        PartUtilizada: "Folha\r\n",
        FormUtilizacao: "Extrato\/Tintura\r\n",
        Posologia: "Dose Diária: 400 a 840 mg de derivados de Hidroquinonas expressos em arbutina.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto \/ Infantil\r\n",
        Ind: "Infecções do trato urinário.\r\n",
        ContraInd: "Não utilizar continuamente por mais de uma semana nem por mais de cinco semanas\/ano.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Não usar em crianças menores de 12 anos. Restrito à Prescrição Médica\r\n"
    },
    {
        ID: 86,
        Fitoterapicos: "Valeriana\r\n",
        Nomebot: "Valeriana officialies\r\n",
        PartUtilizada: "Raízes\r\n",
        FormUtilizacao: "Extratos\/tintura\r\n",
        Posologia: "Dose Diária: 1,0 a 7,5 mg de ácidos sesquiterpênicos expressos em ácido valerênico.\r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n",
        Ind: "Sedativo moderado, hipnótico e no tratamento de distúrbios do sono.\r\n",
        ContraInd: "Não constam.\r\n",
        Efeitos: "Não constam.\r\n",
        InfoAdic: "Restrito à Prescrição Médica\r\n"
    },
    {
        ID: 87,
        Fitoterapicos: "Zedoária\r\n",
        Nomebot: "Zedoaria officinalis\r\n",
        PartUtilizada: "Rizoma\r\n",
        FormUtilizacao: "Pó.\r\n",
        Posologia: "1g duas a três vezes ao dia \r\n",
        Via: "Oral\r\n",
        Uso: "Adulto\r\n ",
        Ind: "Gastrite, mau hálito, mádigestão, flatulências, cálculos renais, gota, hipercolesterolemia, tosse, bronquites e insônia.\r\n",
        ContraInd: "Nos três primeiros meses de gestação e lactação.\r\n",
        Efeitos: "Diarreias, inchaço e dores abdominais\r\n",
        InfoAdic: "Não constam.\r\n"
    }
]