export const suplementos = [
    {
        ID: 1,
        Suplemento: 'Ácido Alfa Lipóico',
        Descr: 'É sintetizado naturalmente pelo organismo. Primeira indicação para tratamento de disfunções hepáticas e como antídoto ao envenenamento causado pelo fungo Amanita phalloides. Possui também propriedades antioxidantes potentes e de amplo espectro, sendo, um inibidor significativo de radicas-livres.  Diabetes: Útil nas complicações diabéticas como danos neurológicos e catarata como tratamento preventivo.  Colesterol: Em associação com T4, proporciona diminuições nos níveis séricos do colesterol e não afeta a taxa de triglicerídeos.  Cirrose Hepática: Resultados satisfatórios no tratamento.  Rins: Estudos mostram prevenção da formação de cristais de oxalato de cálcio em rins de animais de laboratório.  Sistema Nervoso: Estimulação de fatores de crescimento de nervos. Possui efeito neuroprotetor.',
        Ind: 'Uso Interno: Prevenção de danos hepáticos nas intoxicações, Envenenamentos por cogumelos do gênero Amanita phalloides, Coadjuvante no tratamento da cirrose hepática em alcoólatras, antioxidante, prevenção da lipoperoxidação, danos oxidativos ao DNA e às proteínas. Medicina ortomolecular: coadjuvante na terapia do diabetes e da catarata, pacientes com AIDS.  Uso Tópico: Anti-inflamatório, antioxidante, diminuição de linhas finas.Prevenção de eritema associado a exposição à radiação ultravioleta ',
        Posologia: 'Hepatoprotetor – 10 a 30 mg/dia, antioxidante – 100 a 600 mg/dia, uso tópico – 1,0 a 5%',
        Reacoes: 'Raras reações cutâneas alérgicas, sintomas gastrointestinais e relacionados à hipoglicemia.',
        ContraInd: 'Pacientes diabéticos, distúrbios da tiroide, hipersensibilidade ao ácido alfa lipóico.',

    },
    {
        ID: 2,
        Suplemento: 'Albumina',
        Descr: 'A albumina é uma proteína presente principalmente na clara do ovo e é utilizada como suplemento alimentar para ganho de massa muscular. Além disso, a albumina é também produzida no fígado para ajudar na formação de hormônios e manter o organismo hidratado. ',
        Ind: 'Atletas que queiram ganhar massa muscular e evitar lesões musculares, pacientes grandes queimados (protocolo de infusão de albumina).',
        Posologia: '10 a 40g ao dia',
        Reacoes: 'Desconforto gastrointestinal e flatulência.',
        ContraInd: 'Como qualquer proteína, o excesso é excretado nas fezes ou acumulado como gordura. A albumina está contraindicada para hipertensos, anemia grave, varizes no esôfago, edema pulmonar, problemas renais, doenças no fígado, problemas de coagulação. O uso em excesso pode prejudicar o fígado.',
    },
    {
        ID: 3,
        Suplemento: 'BCAA (leucina, isoleucina, valina)',
        Descr: 'É um suplemento composto pelos aminoácidos de cadeia ramificada leucina, isoleucina e valina. O BCAA serve como transportadores de nitrogênio, nutriente que atua na síntese de outros aminoácidos como glutamina e alanina necessários para a produção de novas fibras musculares (anabolismo) e síntese proteica. Outra função dos BCAAs é estimular a produção de insulina, hormônio que promove a entrada de glicose e aminoácidos nas células. Esses efeitos do BCAA ajudam a diminuir os danos musculares resultantes da prática esportiva, aceleram a recuperação muscular, estimulam a síntese de proteínas e reduzem a fadiga. O BCAA também garante mais energia aos músculos durante o treino, o que pode se traduzir em séries mais intensas e um treino mais longo e produtivo.',
        Ind: 'Redução da fadiga, prevenção de perda massa magra, melhora da recuperação muscular.',
        Posologia: 'Dose recomendada de BCAA por dia é de 0.20 gramas/kg. Para uma pessoa de 70 kg cerca de 14g/dia dividida em 30 minutos antes e 30 após o exercício.',
        Reacoes: 'Não constam.',
        ContraInd: 'Indivíduos com histórico de doenças renais devem evitar o uso. Pode ocasionar desidratação devido à metabolização dos aminoácidos.',
    },
    {
        ID: 4,
        Suplemento: 'Betacaroteno',
        Descr: 'O betacaroteno é um carotenoide precursor da vitamina A. Apresenta papel importante na eliminação de radicais livres e previne sua formação. É conhecido como pró-vitamina A porque uma molécula de betacaroteno pode ser dividida em duas moléculas de vitamina A. Se a quantidade de vitamina A é suficiente, o betacaroteno é armazenado até que seja solicitado pelo organismo. Entre outras funções, esta pró-vitamina pode ser uma aliada para combater a agressão dos radicais livres originados pela exposição solar, reações alérgicas ao sol ou mesmo as queimaduras. Além disso, favorece a obtenção de um bronzeamento na pele, oprocesso todo irá auxiliar também na formação da melanina, que é o pigmento da pele que é responsável por protegê-la dos raios ultravioletas e manter o bronzeado por mais tempo. Encontrado em cápsulas isoladas ou em associação com outras vitaminas e minerais.',
        Ind: 'Prevenção do envelhecimento inibindo a formação de radicais livres no organismo, desenvolvimento dos dentes e ossos, aumento da imunidade, elasticidade à pele, aumenta do brilho dos cabelos, fortalecimento das unhas, bronzeamento mais duradouro e uniforme.',
        Posologia: '100mg ao dia',
        Reacoes: 'Não constam.',
        ContraInd: 'O betacaroteno não provoca toxicidade, pois sua conversão é regulada pela presença de vitamina A já existente. Estudos recentes mostram interação da suplementação do betacaroteno com danos ao fígado, sendo assim não mostrando efeito benéfico de proteção contra câncer e sistema cardiovascular.',
    },
    {
        ID: 5,
        Suplemento: 'Boro',
        Descr: 'O boro tem influência no metabolismo dos hormônios da tireoide e regula a permeabilidade da membrana celular. O Boro otimiza o metabolismo do cálcio, potássio, magnésio e vitamina D. Sua carência traz transtornos nutricionais caracterizados por hiperparatireodismo secundário, atraso no crescimento e nas mulheres após menopausa a falta de boro contribui para maior eliminação de cálcio e magnésio pela urina, reduzindo concentrações séricas dos hormônios estradiol e testosterona.',
        Ind: 'Prevenção da perda de cálcio e a desmineralização óssea (osteoporose) em mulheres na menopausa.',
        Posologia: '1 a 5mg de boro elementar ao dia.',
        Reacoes: 'Os sinais de toxicidade aguda incluem náuseas, vômitos, diarreia, dermatites e letargia.',
        ContraInd: 'Os sinais de toxicidade aguda incluem náuseas, vômitos, diarreia, dermatites e letargia.',
    },
    {
        ID: 6,
        Suplemento: 'Cafeína',
        Descr: 'A cafeína tem sido utilizada como substância ergogênica, pois possui mecanismos que podem desencadear importantes alterações metabólicas e fisiológicas, resultando na melhoria do desempenho atlético. A cafeína é um ativo estimulante que induz o organismo a produzir mais energia, através da ação lipolítica o que favorece maior oxidação de gorduras, redução da utilização de glicogênio muscular, auxilia no aumento da resistência aeróbia durante os exercícios físicos de longa duração e favorece a definição dos grupos musculares. Contribui também para retardar o aparecimento da fadiga. Além de suplementos esportivos a cafeína é encontrada em medicamentos para dor de cabeça por ser estimulante do sistema nervoso central.',
        Ind: 'Atividade física, definição muscular, controle de peso e emagrecimento, aumento da resistência aeróbica, rendimento físico e revigoramento, melhora da concentração como estimulante para os estudos, emagrecimento e respiração.',
        Posologia: '100 a 400mg dia.',
        Reacoes: 'Agitação e insônia.',
        ContraInd: 'Crianças, grávidas, amamentação, hipertensão, doenças do coração, úlceras, insônia, disfunção hepática.',
    },
    {
        ID: 7,
        Suplemento: 'Cálcio',
        Descr: 'Esse mineral é essencial na formação de tecidos, ossos e dentes, na oxigenação dos tecidos. Com o sódio, o potássio e o magnésio controlam a atividade cardíaca e os vasos sanguíneos, participa da contração das musculaturas lisas e estriadas. Coadjuvante no tratamento da artrite. A eliminação do cálcio ocorre pela urina, fezes e suor, a ingestão de quantidades insuficientes por períodos prolongados pode afetar diversos processos biológicos. Sua falta causa osteopenia e osteoporose, perda do osso da mandíbula, problemas de saúde bucal e hipertensão. A suplementação não é recomendada para pessoas com doenças renais, histórico de pedras nos rins e gastrite.',
        Ind: 'Tratamento de osteoporose já estabelecida, em indivíduos que não ingerem níveis adequados de cálcio.',
        Posologia: 'De acordo com a DRIS.',
        Reacoes: 'Raro, pode causar problemas gastrointestinais.',
        ContraInd: 'Problemas renais graves, hipercalcemia, hipercalciúria grave, hipervitaminose D. Gestantes somente com recomendação médica e dentista.',
    },
    {
        ID: 8,
        Suplemento: 'Coenzima Q10',
        Descr: 'Participa da produção de energia, é encontrada em todas as células do corpo, exerce um importante papel na saúde do coração e na função cardiovascular, pois ajuda na produção de ATP (energia celular) para ajudar a manter um batimento cardíaco estável. Entre outras indicações, também é utilizada nas doenças imunológicas, pois aumenta a relação de linfócitos CD4/CD8 em portadores de HIV e doenças consumptivas. Diminui a incidência de infecções oportunistas. Melhora o transporte de oxigênio aos tecidos, como em portadores de doenças pulmonares obstrutivas. Tem uma boa atividade em algumas formas de distrofias musculares. Como antioxidante a COENZIMA Q10 pode ajudar a desacelerar o envelhecimento precoce, pois ajuda a reduzir os danos causados pelos radicais livres. Esta função também confere à enzima a capacidade de melhorar a saúde do sistema imunológico e reduzir os danos oxidativos por todo o organismo. A deficiência é rara, os sintomas geralmente são fraqueza fadiga e convulsões.',
        Ind: 'Doenças cardiovasculares como insuficiência cardíaca, insuficiência coronariana, hipertensão arterial, prolapso da válvula mitral, síndrome da isquemiareperfusão, estenose aórtica. Doenças não cardiovasculares como doenças periodontais, deficiências imunológicas, doenças neuromusculares, doenças pulmonares crônicas.',
        Posologia: 'Na literatura, as doses recomendadas variam de 10 a 200mg ao dia, fracionadas ou não, de acordo com a gravidade da patologia. Recomendam-se doses mais altas em pacientes portadores de patologias cardiovasculares graves, distrofias musculares e pacientes imunocomprometidos.',
        Reacoes: 'Raro: desconforto epigástrico, náuseas, perde de apetite e diarreia.',
        ContraInd: 'Em pacientes que apresentem hipersensibilidade. A coenzima Q10 não foi estudada durante os períodos de gestação e lactação. ',
    },
    {
        ID: 9,
        Suplemento: 'Condroitina (sulfato de condroitina)',
        Descr: 'Utilizada geralmente em conjunto com a glucosamina. Estimula a produção de proteínas que mantem a elasticidade da cartilagem ajudando a manter as articulações saudáveis. O sulfato de condroitina é um dos principais componentes estruturais da cartilagem e provê grande parte de sua resistência e compressão. Juntamente com a glucosamina, sulfato de condroitina tornou- se bastante usado como suplemento alimentar para tratamento de osteoartrite. É utilizado também em cremes para a reposição da flexibilidade e maciez à pele seca, causadas pelo uso frequente de detergentes ou bronzeadores, e pela exposição à água clorada de piscinas, à água do mar e ao sol. O sulfato de condroitina é usado em formulações hidratantes para estética corporal em formulações rejuvenescedoras.',
        Ind: 'Osteoartrite, osteoartrose ou artrose em todas as suas manifestações.',
        Posologia: '800 a 1200mg diárias em doses únicas ou fracionadas.',
        Reacoes: 'São raros, podem apresentar sintomas como náuseas e mal estar digestivo em alguns casos.',
        ContraInd: 'Durante a lactação e em pacientes que apresentem hipersensibilidade. Não possui estudos com gestantes.',
    },
    {
        ID: 10,
        Suplemento: 'Substância produzida pelo fígado através de 3 aminoácidos (arginina, glicina, metionina) e encontrada nos músculos, para fornecer energia, no sangue e na urina. Tem aparência cristalina, branca e fortemente alcalina. O corpo produz cerca de 2g de creatina, sendo o suficiente parao dia. No corpo é capaz também de reter água na fibra muscular. Encontrada na forma monoidratada nos suplementos, em pó, tabletes ou cápsulas.',
        Descr: 'Para aumentar performance atlética em adultos, tratamento de deficiência de guanidinoacetato metiltransferase em crianças',
        Ind: 'Para aumentar performance atlética em adultos, tratamento de deficiência de guanidinoacetato metiltransferase em crianças',
        Posologia: 'A dose inicial é de 20 g/dia por 5 a 7 dias, depois 5 g/dia para aumentar a performance atlética. Geralmente é utilizada por períodos determinados de tempo. Para crianças em tratamento para deficiência de guanidinoacetato metiltransferase:2 g/kg/dia.',
        Reacoes: 'Diminuição da síntese endógena pelo seu uso via exógena, câimbras e cansaço muscular, retenção hídrica.',
        ContraInd: 'Alergia a creatina, Função renal comprometida (excreção da creatina é feita pela urina), desidratação e pessoas em uso de diurético. O uso prolongado e em doses altas pode contribuir para alterações renais.',
    },
    {
        ID: 11,
        Suplemento: 'Cromo',
        Descr: 'Age no metabolismo de gorduras e carboidratos, estimula a síntese de ácidos graxos e colesterol, age nos receptores das células do pâncreas, aumentando a efetividade da insulina para facilitar a entrada de glicose no interior das células. Deficiência de cromo na dieta aumenta o colesterol e triglicerídeos, placas de gorduras nas artérias, insulina circulante aumenta sem ser utilizada pelas células. Podem ocorrer sintomas de intolerância à glicose em pessoas mais velhas com diabetes mellitus não dependentes de insulina e em lactentes com desnutrição proteico- calórica, hipoglicemia, visão turva, sudorese, fadiga, tremores e imunodeficiência geral. Cromo inalado em indústrias tem sido associado ao câncer de pulmão.',
        Ind: 'Pacientes que controlam níveis glicêmicos só com dieta.',
        Posologia: 'Conforme DRIs',
        Reacoes: 'Não existem relatos de reações adversas em longo prazo do uso de suplementação de cromo. Podem existir alguns efeitos secundários como dor de cabeça, perda de apetite, náuseas e vômitos, tontura e cansaço',
        ContraInd: 'O cromo pode competir com o ferro e zinco no organismo, podendo levar a anemia e deficiência de zinco.',
    },
    {
        ID: 12,
        Suplemento: 'EXSYNUTRIMENT®',
        Descr: 'Suplemento patenteado do silício orgânico.ExSyNutriment é uma forma estabilizada e concentrada de Silício Orgânico, atua no tecido conjuntivo, reestruturando as fibras de colágeno e elastina, resultando na reestruturação e firmeza da pele.',
        Ind: 'Alta hidratação cutânea, fortalecedor de unhas, cabelos mais resistentes e espessos, aumento da síntese de colágeno e elastina, manutenção da elasticidade das paredes dos vasos sanguíneos e do miocárdio,potencializa a fixação de cálcio no tecido ósseo, repõe silício orgânico que diminui com o envelhecimento.',
        Posologia: 'Associado a outros ativos 100 a 300mg/dia, Isolado 300 a 600mg/dia.',
        Reacoes: 'Não constam',
        ContraInd: 'Ingerir longe das refeições. 1 hora antes ou 2 horas depois da ingestão de alimentos.',
    },
    {
        ID: 13,
        Suplemento: 'Fabuless®',
        Descr: 'Fabuless é um suplemento natural elaborado por meio do óleo de palma e aveiapurificadas, no qual pode ser utilizado junto a alimentos para pessoas que desejam emagrecer. Dentre suas propriedades encontram controle da saciedade e a diminuição da vontade de comer. Com isso o fármaco auxilia no emagrecimento.',
        Ind: 'É indicado para pessoas que estão acima do peso, ou a pessoas que desejam gerenciar seu peso por meio do controle da fome e da redução de ingestão calórica.Efeitosde saciedade duram de 4 a 8 horas, podendo se estender por mais tempo.',
        Posologia: 'Encontrado geralmente em sachês de 6g com indicação de 1 a 2 sachês ao dia junto com algum alimento',
        Reacoes: 'Não constam.',
        ContraInd: 'Desaconselhável para gestantes e lactantes.',
    },
    {
        ID: 14,
        Suplemento: 'Ferro',
        Descr: 'Esse mineral é essencial na formação dos glóbulos vermelhos, essenciais para o transporte de oxigênio pelo organismo. A deficiência de ferro pode provocar anemia ferropriva e sintomas como vertigens, perda de cabelos, cansaço, fissuras nos lábios, nervosismo e palidez. Na gestação é necessário aumentar a fonte desse mineral. Interage com a vitamina B12 e o ácido fólico. Suplementação pode ser apresentada como Sulfato Ferroso.',
        Ind: 'Tratamento de anemia ferropriva (Sulfato ferroso).',
        Posologia: 'De acordo com DRIs.',
        Reacoes: 'Normalmente o sulfato ferroso é bem tolerado. Alguns pacientes podem apresentar distúrbios gástricos como náuseas, vômitos e dor epigástrica. Outros efeitos mais graves, incluindo crises hemolíticas perigosas, estão ligados a altas dosagens.',
        ContraInd: 'Sulfato ferroso aos portadores de tuberculose e intolerância gástrica ao ferro. Nas septicemias e menorragias, hipertensos e em idosos.',
    },
    {
        ID: 15,
        Suplemento: 'Glicina',
        Descr: 'Aminoácido não essencial que desempenha um papel importante na formação dos sais biliares. É necessário para síntese de glicose e da creatinina, função importante na glândula pituitária e na produção de energia, estimula a liberação de glucagon pelo pâncreas. É utilizado como suplemento dietético, em antiácidos para o tratamento da hiperacidez gástrica, como um ingrediente de alguns comprimidos de aspirina com o objetivo de reduzir irritação gástrica, usado como solução de irrigação urogenital durante certos procedimentos cirúrgicos. Pode ser encontrado como glicinato férrico e glicinato de magnésio.',
        Ind: 'Glicinato férrico: para anemias. Glicinato de magnésio: para casos de cansaço físico e mental por melhorar a absorção do magnésio, mineral muito importante para contração muscular e transmissão de impulsos nervosos. Tratamento de acidez gástrica, distrofia muscular gástrica, deficiência proteica, hipoproteinemia, desnutrição. ',
        Posologia: 'De acordo com faixa etária e indicação. Geralmente é utilizado de 20 a 200mg ao dia.',
        Reacoes: 'Apresentam-se somente por sua aplicação parenteral em forma de distúrbios digestivos (náuseas, vômitos) ou reações febris.',
        ContraInd: 'Insuficiência hepática ou renal grave, anúria.',
    },
    {
        ID: 16,
        Suplemento: 'Gluconamam®',
        Descr: 'Glucomanan é uma fibra solúvel de alto peso molecular, quimicamente relacionada à celulose, derivada da raiz de Konjac que é uma planta medicinal chamada cientificamente de Amorphophallus konjac. Tem propriedade de absorver muitas vezes o seu peso em água, formando um gel. Forma também um revestimento em torno das partículas alimentares, que retarda o processo da digestão. O glucomannan promove também uma redução nos níveis plasmáticos de colesterol e triglicérides. Por sua propriedade formadora de massa é usado também na constipação crônica. O glucomannan pode também ser usado como excipiente em diversas formulações em cápsulas. ',
        Ind: 'É usada no tratamento adjuvante da obesidade, por sua propriedade formadora de massa, que proporciona a sensação de plenitude gástrica, constipação crônica, coadjuvante no tratamento de colesterol, triglicérides e diabetes.',
        Posologia: 'A posologia usual é de 500 a 2000mg ao dia, duas horas antes das refeições, juntamente com dois copos d´água.',
        Reacoes: 'Obstrução esofágica associada ao glucomannan.',
        ContraInd: 'Estenose esofágica ou pilórica. Contra indicado para pacientes com dificuldade de deglutição. Recomenda- se não administrar com nenhum outro medicamento, já que pode reduzir de forma importante sua absorção.',
    },
    {
        ID: 17,
        Suplemento: 'Glucosamina',
        Descr: 'É encontrada na forma de sulfato de glucosamina ou glucosamina sulfato potássico como suplemento. A glucosamina é uma molécula de ocorrência natural (aminoaçúcar) que integra a matriz da cartilagem articular e o ácido hialurônico. A glucosamina está envolvida na formação da cartilagem articular e também estimula a produção do ácido hialurônico no líquido sinovial. Ela parece ter um papel na recuperação da degeneração cartilaginosa, através da substituição da matriz hialínica e interferindo na sua degradação. Como consequência, retarda a progressão da osteoartrite. Sua ação, no alívio dos sintomas, é comparável à do ibuprofeno. A Glucosamina pode agir de forma mais efetiva quando junto da vitamina C, ajudando o corpo a produzir e estabilizar colágeno saudável nos tecidos de conectividade. É utilizada em medicamentos em conjunto com a condroitina.',
        Ind: 'Artrose primária e secundária (dor e limitação do movimento), osteocondroartrose, espondilose, condromalasia rotular periartrite escapulo- umeral, reumatismo articular; redução de lesões artrósicas com ação anti- inflamatória, rigidez articular e diminuição de mobilidade articular, protetor das cartilagens, fortalecimento dos tecidos de conectividade (cartilagem, ligamentos e tendões), regeneração de cartilagem danificada para reparar as funções da articulação e mobilidade, e ajudar na recuperação de lesões.',
        Posologia: 'A dose diária recomendada é de 1,5g por dia.',
        Reacoes: 'Desconforto gástrico; náuseas, diarreia; flatulência; constipação; erupção cutânea com coceira e vermelhidão.',
        ContraInd: 'Hipersensibilidade à glucosamina, gravidez, lactação, fenilcetonúria, a administração a doentes com insuficiência renal ou hepática grave deve ser feita sob vigilância médica.',
    },
    {
        ID: 18,
        Suplemento: 'HMB (beta-hidroxi-beta-metilbutirato)',
        Descr: 'O hidroximetilbutirato (HMB) é um metabólito natural do aminoácido leucina que é um aminoácido essencial e, por esta razão também é chamado de metabólito da leucina. O HMB é produzido pelo organismo e não é considerado um nutriente essencial. Estudos sugerem que o HMB tem ação no aumento da massa muscular pela prevenção da degradação proteica que ocorre com a prática de exercícios intensos e de resistência e teria atuação no aumento do processo de reconstituição dos tecidos. Outros estudos mostram que auxilia na redução do teor de gordura corporal e que poderia ajudar na saúde das artérias e redução dos níveis de colesterol. Não há especificações na literatura sobre a carência de HMB, uma vez que o nosso corpo produz pelo menos uma quantidade mínima desta substância. Substância ainda está sendo estudada.',
        Ind: 'Aumento da força, aumento da massa corporal magra, diminuição do catabolismo proteico, redução de gordura corporal.',
        Posologia: 'Conforme demonstrado nos estudos humanos, é recomendável a administração de 1,5 a 3g. Preferencialmente meia hora antes do treinamento.',
        Reacoes: 'Não existem reações adversas reconhecidas até o momento.',
        ContraInd: 'Alguns estudos sugeriram que o seu uso poderia estar associado a problemas renais, porém não foi comprovado.',
    },
    {
        ID: 19,
        Suplemento: 'Inositol',
        Descr: 'O inositol é um composto do metabolismo da glicose, na literatura científica também é discutível se é classificado como vitamina do complexo B, pois nenhuma síndrome de deficiência de inositol foi identificada no ser humano não sendo classificado como vitamina. Tem como principal função neutralizar o colesterol, pois auxilia na quebra de gorduras, portanto, pode haver diminuição nos níveis de colesterol com o uso de inositol em associação a colina. É um importante componente do organismo por participar da formação de parte das membranas celulares, representando entre 2 e 12% do total de todos os tecidos do corpo humano. Age no funcionamento do sistema nervoso, nutrindo as células cerebrais, auxilia a transmissão de impulsos nervosos, melhora a comunicação cerebral, memória e inteligência. Estudos sugerem que a sua deficiência parece estar associada à coceira, escamação na pele, constipação intestinal (prisão de ventre), queda de cabelo e aumento nos níveis de colesterol.',
        Ind: 'Redução dos níveis de colesterol no sangue, modulador da atividade da insulina, quebra das gorduras. Doenças Psicológicas: pacientes acometidos de depressão geralmente apresentam redução dos níveis de inositol no líquido cefalorraquidiano (cerebrospinal). Alguns resultados preliminares de estudos com suplementos de inositol revelam promissores avanços para pessoas que sofrem de distúrbios tais como bulimia, síndrome do pânico, transtorno obsessivo-compulsivo (TOC) e transtornos bipolares. ',
        Posologia: 'Doses diárias 500 a 1000mg.',
        Reacoes: 'Pode provocar desconfortos intestinais.',
        ContraInd: 'Utilizar com cautela em pacientes diabéticos, em tratamento com insulina ou antidiabéticos orais.',
    },
    {
        ID: 20,
        Suplemento: 'Iodo',
        Descr: 'Garante o bom funcionamento da tireoide e do cérebro, facilita o armazenamento de oxigênio pelos músculos, evita a deposição de gordura nos tecidos. Sua deficiência pode causar bócio, atraso no crescimento e desenvolvimento sexual das crianças. Suplemento encontrado na forma de iodo inorgânico, iodo quelato e iodeto de potássio.',
        Ind: 'Tratamento de doenças da tireoide, estudos mostram eficácia no tratamento de doenças fibrocísticas e sinusite crônica.',
        Posologia: 'De acordo com o tipo de suplemento escolhido.',
        Reacoes: 'Desconforto gastrintestinal como náuseas e vômitos, cansaço e tontura.',
        ContraInd: 'Hipersensibilidade ao iodo. Iodeto de potássio não é indicado para gestantes até o 3º mês e período de lactação, insuficiência renal e hepática, tuberculose pulmonar ativa, em idosos deve ser acompanhada com atenção.',
    },
    {
        ID: 21,
        Suplemento: 'L- Taurina',
        Descr: 'A taurina é um aminoácido não essencial, estando presente em abundância no organismo. É sintetizada no fígado e cérebro a partir da metionina e cisteína. Possui diversas funções dentre elas desintoxicação, facilita a excreção de substâncias pelo fígado, fortalece e aumenta a força das contrações cardíacas, estabiliza as membranas celulares do cérebro e coração, tem ação antioxidante combatendo radicais livres que danificam as células. Há relatos em alguns estudos que a taurina traz benefícios a paciente epiléticos. Participa da síntese de ácidos biliares, como o acido taurocólico, ativa a formação de ácido gama-amino butírico (GABA) e dificulta a transmissão de catecolaminas e da acetilcolina. É encontrada somente em alimentos de origem animal, sendo os vegetarianos pacientes em risco para deficiência de taurina.',
        Ind: 'Suplementação para ganho de massa muscular em associação com outros aminoácidos. Vegetarianos. Fadiga. Tratamento de hipercolesterolemia e de doenças cardiovasculares.',
        Posologia: 'É usada na faixa de 100 a 600mg ao dia, como suplemento dietético e de 1 a 3 g ao dia em doenças cardiovasculares.',
        Reacoes: 'Não constam.',
        ContraInd: 'Altas doses podem sobrecarregar fígado e rins. Contra indicado para pacientes com doenças renais.',
    },
    {
        ID: 22,
        Suplemento: 'L-arginina',
        Descr: 'Arginina é um aminoácido não essencial. Percursora de óxido nítrico desempenha papel importante na pressão sanguínea e fluxo de sangue, contribuindo para melhora da função vascular, pressão arterial, problemas cardiovasculares e disfunção erétil (impotência), reforça o sistema imunitário e ajuda no processo de cicatrização, favorece o crescimento muscular infantil e do adolescente. Encontrado em suplementos esportivos e como aspartato de L-arginina (comprimidos ou comprimidos efervescentes). Muito utilizada em esportistas por ser um aminoácido, contribuindo para ganho de massa muscular.',
        Ind: 'Está indicado para o tratamento dos diversos tipos de astenia e de fadigas física e mental.',
        Posologia: 'Indicação recomendada do fabricante, geralmente 1,5 a 3g de arginina de 15 a 30 dias.',
        Reacoes: 'Geralmente é bem tolerado, sendo raros sintomas como náuseas, diarreias, cólicas e distensões abdominais.',
        ContraInd: 'Não há estudos em crianças, sendo contraindicado para essa faixa etária.',
    },
    {
        ID: 23,
        Suplemento: 'L-carnitina',
        Descr: 'A carnitina é um elemento sintetizado naturalmente pelo organismo a partir de um aminoácido essencial (lisina), presente nos alimentos como a carne vermelha, por exemplo. A L-carnitina é produzida pelo organismo quando o gasto energético aumenta e é necessário utilizar a gordura corporal como fonte de energia para manter o bom funcionamento do corpo. Impede a formação de níveis excessivos de triglicérides, normaliza o quadro lipoproteico (redução das lipoproteínas de densidade muito baixa e aumento das lipoproteínas de alta densidade) eliminando, portanto um dos mais importantes fatores de risco de doenças cardiovasculares (aterosclerose e afecções cardíacas consequentes).',
        Ind: 'Carência de carnitina, déficit de carnitina induzido por esforço, aumento do rendimento muscular.',
        Posologia: 'Verificar informações do fabricante.',
        Reacoes: 'É bem tolerada, sintomas gastrointestinais são raros.',
        ContraInd: 'Para pacientes que possuem hipersensibilidade a carnitina.',
    },
    {
        ID: 24,
        Suplemento: 'L-Cisteína',
        Descr: 'Aminoácido essencial, sintetizado a partir da metionina, participa de diversos processos como desintoxicação, eliminação de radicais livres (efeito antioxidante), proteçãodas células hepáticas cerebrais contra álcool e fumo, fluidificação e remoção do muco do trato respiratório e remoção do excesso de cobre do organismo. Também é utilizada para tratamento da alopecia, a cisteína é importante para o crescimento do cabelo, assim é utilizada também em produtos de tratamento para cabelos fracos que precisam ser fortalecidos. Prevenção de ulceras de córnea em forma de colírio e após queimaduras químicas. ',
        Ind: 'Complemento dos requerimentos nutricionais das crianças que recebem alimentação por via parenteral total. É também indicado para preparações cosméticas para o cabelo, doenças de pele, entre outros.',
        Posologia: 'Administra-se diluída na solução de aminoácidos utilizada para nutrição parenteral total, em uma proporção de 0,5g de cloridrato de cisteína cada 12,5g de aminoácidos. Via oral é usada na faixa de 100 a 500mg ao dia, verificar DRI para a faixa etária.',
        Reacoes: 'Transtornos digestivos (náuseas, vômitos) ou reações febris.',
        ContraInd: 'Seu efeito sobre o feto é desconhecido, por isso se deve administrar na gestante somente se for claramente necessário.',
    },
    {
        ID: 25,
        Suplemento: 'L-Glutamina',
        Descr: 'Glutamina é um aminoácido condicionalmente essencial e presente em grande quantidade no corpo, é armazenado principalmente nos músculos. Atua como substrato ergogênico (combustível) para as células do sistema imune (linfócitos, fibroblastos) e do intestino (enterócitos) e como combustível respiratório primário. A glutamina é extremamente importante para manutenção da saúde do tecido que reveste todo o intestino. Sendo assim, fundamental para que o sistema imunológico, conservação do intestino, diminuição da permeabilidade intestinal e melhoria da imunidade. Situações podem diminuir os níveis de glutamina severamente no músculo, como em exercícios extenuantes, cirurgias de grande porte, processos catabólicos extremos (queimaduras, infecções). ',
        Ind: 'Melhora do sistema imunológico, conservação da integridade e diminuição da permeabilidadeda mucosa intestinal, doenças intestinais, paciente imunodeprimidos, sépticos, com risco de translocação bacteriana, redução de perda de massa muscular, suplementação para atletas de alta performance, para recuperação do estresse físico causada por exercícios.',
        Posologia: '5 a 10g dia. Avaliar individualmente.',
        Reacoes: 'Sintomas de desconforto gastrointestinal podem ser comuns.',
        ContraInd: 'Pacientes com restrição proteica por patologias hepática e renal ou por qualquer indicação do médico.Em excesso pode causar danos aos rins.',
    },
    {
        ID: 26,
        Suplemento: 'L-Lisina',
        Descr: 'A lisina é um aminoácido essencial, obtido através de alimentos, é importante na formação de proteínas, como o colágeno, na prevenção e tratamento do vírus do herpes, ajuda a fortalecer o sistema imunológico e a facilitar a absorção do cálcio. A deficiência de lisina pode causar fadiga, náusea, tontura, olhos irritados, perda de apetite, anemia, crescimento lento e distúrbios reprodutivos.',
        Ind: 'Formação e manutenção de massa muscular por ser um aminoácido essencial, prevenção e tratamento do vírus do herpes.',
        Posologia: '500 a 3000mg /dia.',
        Reacoes: 'Desconfortos gastrointestinais como dor no estômago e diarreias.',
        ContraInd: 'Seu uso prolongado pode desequilibrar as quantidades de arginina no organismo. Utilizar com cuidado em pacientes com doenças renais ou hepáticas. Contra indicado para gestantes e lactantes.',
    },
    {
        ID: 27,
        Suplemento: 'L-Tirosina',
        Descr: 'É um aminoácido não essencial sintetizado a partir da fenilalanina, participa da síntese de epinefrina, dopamina, melanina, e nas funções da adrenal, tireoide e pituitária. Possui ação efetiva antidepressiva causada pela deficiência da norepinefrina, estimulante cerebral no déficit de memória e na dificuldade de atenção e concentração. Atua como substrato na síntese de neurotransmissores (dopamina, epinefrina e norepinefrina). É um aminoácido não essencial usado no tratamento dos distúrbios do sono e na abstinência ao uso de drogas.',
        Ind: 'Suplemento dietético utilizado em dietas enterais e oral, tratamento da ansiedade distúrbios do sono depressão e na abstinência ao uso de drogas, crescimento infantil, regulação hormonal, estimulante cerebral, doença de Basedow.',
        Posologia: '50 a 300mg/dia',
        Reacoes: 'Não constam.',
        ContraInd: 'A suplementação de L- tirosina é contraindicada a pessoas portadoras de alcaptonúria (oxidação incompleta da fenilalanina e da tirosina), um erro inato do metabolismo que envolve este aminoácido, na insuficiência hepática ou renal grave, anúria, durante a gravidez e lactação.',
    },
    {
        ID: 28,
        Suplemento: 'L-Triptofano',
        Descr: 'O Triptofano é um aminoácido essencial e um precursor da serotonina. Devido à depleção de serotonina no SNC é considerado ser ligado à depressão, sendo usado no tratamento da mesma. O triptofano é extensivamente ligado a albumina sérica e excretado pela urina. A piridoxina e acido ascórbico parecem estar ligados neste metabolismo. A deficiência pode causar baixos níveis de serotonina e assim favorecer a insônia, depressão, ansiedade, impulsividade, irritabilidade, incapacidade de concentração e crescimento deficiente em crianças.',
        Ind: 'Tratamento do stress e hiperatividade (em crianças) e também usado no tratamento da depressão e de distúrbios do sono. Em aplicações farmacêuticas, o L-triptofano é usado como um ingrediente ativo em antidepressivos e hipnóticos.',
        Posologia: 'Tratamento do stress e hiperatividade (em crianças) e também usado no tratamento da depressão e de distúrbios do sono. Em aplicações farmacêuticas, o L-triptofano é usado como um ingrediente ativo em antidepressivos e hipnóticos.',
        Reacoes: 'Náusea, dor de cabeça e tontura.',
        ContraInd: 'O uso do suplemento de triptofano não é orientado para gestantes, lactantes, pessoas com doenças cardiovasculares e tumores carcinoides.',
    },
    {
        ID: 29,
        Suplemento: 'Colabora na formação dos tecidos, ossos e dentes, na metabolização carboidratos, controla a excitabilidade neuromuscular e das fibras do coração, regula o transporte ativo de outros minerais como sódio, cálcio e potássio, está presente na síntese de insulina. Antagonista natural do cálcio. Possui efeitos cardioprotetores, inibe a agregação das plaquetas. A sua deficiência causa perturbações do sono, irritabilidade, aceleração dos batimentos cardíacos, confusão, espasmos musculares, aumento da resposta inflamatória. Suplemento encontrado em formulações ou como cloreto de magnésio, citrato de magnésio, quelato de magnésio.',
        Descr: 'Prevenção da osteoporose, dificuldade na evacuação, taquicardia, diabetes. ',
        Ind: 'Prevenção da osteoporose, dificuldade na evacuação, taquicardia, diabetes. ',
        Posologia: 'De acordo com as DRIs e tipo de suplemento escolhido. ',
        Reacoes: 'Diarreia, náuseas e dor abdominal. Em excesso pode causar fadiga e arritmia.',
        ContraInd: 'Pacientes com insuficiência renal. Deve ser evitado em gestantes, pois o magnésio atravessa a placenta podendo interferir nos níveis séricos do feto. Em excesso pode ocasionar hipermagnesemia. ',
    },
    {
        ID: 30,
        Suplemento: 'Maltodextrina',
        Descr: 'A maltodextrina é um carboidrato em pó solúvel em água e obtido através da conversão enzimática do amido de milho. A maior parte deste produto de mercado apresenta, na verdade, uma mistura de três tipos de carboidratos: a maltodextrina, polímeros de glicose e a frutose. É considerado um produto energético, de moderada a alta absorção pelo organismo, de fácil digestibilidade e com ótima taxa de esvaziamento gástrico. Possui alto nível glicêmico, ou seja, promove elevação no nível de glicose no sangue. É capaz de restabelecer as reservas energéticas de modo prático e satisfatório, melhorando assim o desempenho de praticantes de exercícios físicos e atletas de muitas modalidades, assim como jogadores de futebol, basquete, maratonistas, praticantes de musculação, etc.',
        Ind: 'Exercícios físicos, atletas, competições esportivas, para evitar e reduzir a sensação fadiga durante o treino preservando os estoques de glicose no músculo',
        Posologia: '30g a 40g dissolvidos em 300 ml de água. ',
        Reacoes: 'Não existem estudos que descrevam os efeitos colaterais, mas há relatos de surgimento de acne. ',
        ContraInd: 'Por ser carboidrato de alto índice glicêmico elevando as concentrações de açúcar no sangue não é indicado para diabéticos, e o seu uso sem atividade física pode contribuir para o ganho de peso. ',
    },
    {
        ID: 31,
        Suplemento: 'Manganês',
        Descr: 'Atua no diabetes, aumentando a performance de insulina, está envolvido na síntese do colesterol e metabolismo de gorduras, dos hormônios sexuais e na capacidade reprodutiva, participa da ativação de enzimas como na formação do colágeno, na síntese da ureia, age no aproveitamento do cálcio, fósforo e vitamina B1. A deficiência é rara, os sintomas podem ser tremores, confusão, nível de colesterol elevado, pressão arterial elevada, suores, redução da capacidade mental, batimentos cardíacos elevados. Utilizado na forma quelato de manganês ou manganês elementar. ',
        Ind: 'Utilizado como antioxidante e como suplemento, nos tratamentos em que há aumento na ingestão de cálcio e fósforo, uma vez que estes elementos diminuem a absorção de manganês.',
        Posologia: 'Manganês elementar usado nas concentrações de 2 a 10mg ao dia.',
        Reacoes: 'Não foram observadas em dosagens adequadas.',
        ContraInd: 'O excesso via oral pode ocasionar interação na absorção do ferro causando anemia. A contaminação pelo excesso de manganês (geralmente quando inalado em indústrias) pode acumular no fígado e produzir lesões nervosas que se assemelham ao Parkinson e distúrbios psiquiátricos semelhantes a esquizofrenia. ',
    },
    {
        ID: 32,
        Suplemento: 'Molibdênio',
        Descr: 'O molibdênio é um mineral importante no metabolismo da proteína. Mineral solúvel no intestino delgado participa de reações enzimáticas, como a oxidase hepática. É parte vital de uma enzima responsável pela utilização do ferro em nosso corpo, além de ter ação antioxidante. Ajuda no metabolismo das gorduras e carboidratos, previne a anemia, pode prevenir a impotência sexual, pode produzir sensação de bem estar e auxiliar nas alergias. A deficiência desse mineral é muito rara devido à quantidade recomendada desse mineral ser pequena e facilmente suprida com a alimentação regular. Mas pode ocorrer em casos de subnutrição prolongada, e os sintomas incluem aumento da frequência cardíaca, dificuldade respiratória, náusea, vômito, desorientação e, até o coma. O excesso da ingestão molibdênio pode promover um aumento da concentração de ácido úrico no sangue e dores articulares.',
        Ind: 'Deficiência de molibdênio. Indicado também para atletas.',
        Posologia: '15 a 500 mcg de molibdênio elementar.',
        Reacoes: 'Não constam.',
        ContraInd: 'Pacientes com gota e ácido úrico elevado.',
    },
    {
        ID: 33,
        Suplemento: 'MSM (Metilsulfonilmetano)',
        Descr: 'MSM também conhecido como dimetil sulfona é uma fonte estável do enxofre orgânico. Suplemento nutricional popular usado isoladamente ou em associação com outros nutrientes e apresenta diversos benefícios para pacientes com osteoartrite, além disso, auxilia na manutenção da elasticidade e flexibilidade dos tecidos conectivos que formam as junções e tem ação antioxidante. O MSM representa uma fonte natural de enxofre para o corpo, sendo um componente crítico para a construção dos aminoácidos contidos nas proteínas. O enxofre orgânico é conhecido principalmente pelas suas propriedades de melhorar a circulação e também pela sua ação anti-inflamatória. O enxofre é funcional e estruturalmente importante para mais de 150 compostos orgânicos, incluindo enzimas, tecidos, hormônios, anticorpos e antioxidantes. O enxofre, contido no MSM, está envolvido em quase todos os processos metabólicos do corpo e é essencial na regeneração e nutrição de células saudáveis. ',
        Ind: 'Artrite, osteoartrite. Alguns estudos mostram claramente que o nível de MSM no organismo baixa significativamente com a idade, por isso se faz a indicação do uso de suplemento ao avançar da idade.',
        Posologia: '1.500 a 5.000 mg/dia.',
        Reacoes: 'Não constam.',
        ContraInd: 'Não constam.',
    },
    {
        ID: 34,
        Suplemento: 'Ômega 3',
        Descr: 'O ômega 3 é um ácido graxo essencial que não é produzido pelo organismo, garante o bom funcionamento do cérebro, melhorando a memória e o raciocínio, auxilia na manutenção dos níveis saudáveis de triglicerídeos, previne doenças cardiovasculares, diminui o risco de desenvolvimento de câncer como o câncer de mama, ajuda a combater inflamações, controle da TPM e estresse, melhora o sistema imune, melhora capacidade de aprendizagem.',
        Ind: 'Tratamento coadjuvante de hipertensão arterial, dislipidemias, TPM, gestantes.',
        Posologia: 'A dose diária recomendada de ômega 3 é de 250mg/dia para adultos, 400mg/dia para grávidas e lactantes e de 50 a 100mg/dia para bebês dos 6 a 24 meses.',
        Reacoes: 'Ocorrem geralmente com maior frequência com doses acima de 3000mg/dia. Mais comuns são as náuseas, diarreia, cólicas abdominais, excesso de gases.',
        ContraInd: 'Em doses elevadas, o óleo de peixe pode aumentar o risco de sangramentos, principalmente em pacientes com problemas de coagulação ou medicados com drogas que agem sobre a coagulação, tais como aspirina, clopidogrel, ticlopidina, heparina e varfarina.',
    },
    {
        ID: 35,
        Suplemento: 'Potássio',
        Descr: 'Em conjunto com o sódio, regulariza os batimentos cardíacos e o sistema muscular, pois é necessário para contração muscular e estimula os impulsos nervosos, atua na formação das células, participa da conversão de glicose em glicogênio, é necessário para o funcionamento normal das suprarrenais e do coração. Sua deficiência causa edemas, taquicardia, parada cardíaca, diminuição do rendimento cardíaco, fraqueza geral, irritabilidade, espasmos e dores musculares, paralisia, sensação de formigamento nos pés e mãos, ressecamento da pele, sede, intolerância a glicose, insônia, colesterol elevado, pressão baixa. É comum a deficiência de potássio durante vômitos prologados, diarreias, síndrome de má absorção intestinal e ingestão crônica de laxativos. Suplemento encontrado como fosfato de potássio ou cloreto de potássio.',
        Ind: 'Hipocalemia',
        Posologia: 'Conforme resultados e DRIs, avaliar individualmente.',
        Reacoes: 'Raro, podem ocorrer náuseas, vômitos e desconforto gastrointestinal.',
        ContraInd: 'Hipercalemia de qualquer origem, insuficiência renal grave com oligúria, doença de Addison descompensada, paralisia periódica familiar, desidratação aguda em fase hipovolêmica, diarreia grave, nefropatia com perda de potássio, choque térmico.',
    },
    {
        ID: 36,
        Suplemento: 'Prebióticos',
        Descr: 'São tipos de fibras alimentares, ou seja, carboidratos não digeríveis pelo organismo possuem configuração molecular que os torna resistentes à ação de enzimas. Os prebióticos ajudam na manutenção da flora intestinal, estimulam a motilidade intestinal (trânsito intestinal), contribuem com a consistência normal das fezes, prevenindo assim a diarreia e a constipação intestinal por alterarem a microflora colônica propiciando uma microflora saudável, colaboram para que somente sejam absorvidas pelo intestino as substâncias necessárias, eliminando assim o excesso de glicose (açúcar) e colesterol, possui efeito bifidogênico, isto é, estimulam o crescimento das bifidobactérias. Exemplos de prebióticos são: frutoologosacarídeos (FOS) e a inulina. ',
        Ind: 'Diarreia, constipação, pacientes diabéticos, emagrecimento, obesidade, dislipidemias.',
        Posologia: 'Individualizar para o paciente.',
        Reacoes: 'Em excesso pode causar desconforto intestinal e flatulência.',
        ContraInd: 'Não constam.',
    },
    {
        ID: 37,
        Suplemento: 'Probióticos',
        Descr: ' São microrganismos vivos administrados em quantidades adequadas que aumentam numericamente ou estimulam a proliferação das bactérias benéficas em detrimento das bactérias potencialmente prejudiciais, reforçando os mecanismos naturais de defesa do nosso corpo. Possuem diversos benefícios como: aumentar de maneira significativa o valor nutritivo e terapêutico dos alimentos, pois ocorre um aumento dos níveis de vitaminas do complexo B e aminoácidos. Absorção acrescida de cálcio e ferro; fortalecimento do sistema imunológico, através de uma maior produção de células protetoras; melhor funcionamento do organismo, equilibrando a flora intestinal, atuando no controle do colesterol e na redução do risco de câncer; possuem uma particular importância para os indivíduos com intolerância à lactose, devido ao aumento de uma enzima que facilita a digestão da lactose. Os probióticos são muito usados em iogurtes e leites fermentados, os mais conhecidos são os chamados Lactobacilos.',
        Ind: 'Diarreia, constipação, dislipidemias, vida saudável e ativa.',
        Posologia: 'Individualizado, o uso frequente e regular promove melhor aproveitamento dos probióticos.',
        Reacoes: 'Pode causar desconforto gastrointestinal quando ingerido em excesso.',
        ContraInd: 'O armazenamento deve ser bem feito para não perder as propriedades dos probióticos.',
    },
    {
        ID: 38,
        Suplemento: 'Pycnogenol (Picnogenol)',
        Descr: 'Substância extraída da casca do pinheiro francês (Pinus pinaster). O Pycnogenol possui alto poder anti-inflamatório e antioxidante, sua principal característica. Esta propriedade auxilia na proteção do organismo contra os radicais livres que causam às células. Esses danos celulares causados pelos radicais livres estão associados a diversas doenças, como câncer, infarto e Alzheimer. Cremes à base de pycnogenol ajudam a manter a saúde da pele, também contribuindo para evitar o envelhecimento precoce. Além disso, pode auxiliar no tratamento de problemas circulatórios por seu efeito vasodilatador, aumenta a resistência vascular selando a parede dos vasos danificados, reduz a permeabilidade dos vasos prevenindo o inchaço (edema). Está relacionado também no auxilio a tratamentos de asma, alergias, pressão alta, osteoartrite, dores musculares, diabetes, endometriose, TPM e disfunção erétil. Alguns estudos mostram que o pycnogenol pode atuar no mecanismo de atuação da insulina, sendo capaz de reduzir níveis de glicose no sangue; estímulo à produção de óxido nítrico (NO2) que por sua vez melhora circulação sanguínea. ',
        Ind: 'É comercializado em forma de cápsulas ou em suplementos alimentares',
        Posologia: '200mg/dia, iniciar com doses menores 50 a 100mg/dia. Dose máxima diária 400mg/dia',
        Reacoes: 'Dor de cabeça, desconforto gastrointestinal leve e transitório, tonturas e feridas na boca.',
        ContraInd: 'Recomenda-se que seu uso seja evitado por gestantes, lactantes e crianças até que mais pesquisas conclusivas sejam realizadas. Como o pycnogenol estimula o sistema imune portadores de doenças autoimunes (como: lúpus, esclerose múltipla, artrite reumatoide) devem evitar o seu uso.',
    },
    {
        ID: 39,
        Suplemento: 'SAMe (S-adenosil metionina)',
        Descr: 'SAMe é uma substância presente naturalmente no corpo humano derivada do aminoácido metionina, faz parte de mais de 30 reações metabólicas. Entre outras funções, ele tem importância fundamental na formação de proteínas, hormônios e neurotransmissores. Depressão: Estudos têm sugerido que a S- adenosil- metionina (SAMe) pode ter propriedades antidepressivas moderadamente eficazes por doar metila para muitos neurotransmissores. Fígado:Estudos mostram que o uso de suplementação de SAMe normaliza níveis de enzimas e pode ajudar a tratar doenças crônicas do fígado causadas por alcoolismo e medicação, pois nessas doenças o corpo não é capaz de produzir SAMe. Osteoartrite: Estudos mostraram que SAMe foi capaz de reduzir a dor e inflamação de articulações e pesquisadores arriscam dizer que pode promover a recuperação da cartilagem. Fibromialgia: SAMe pode ser eficaz na redução dos sintomas da fibromialgia, incluindo dor, fadiga, cansaço e depressão. ',
        Ind: 'Como protetor hepático, doenças hepáticas (cirrose aguda e crônica, do tipo biliar, hepatite e colestases, cirros por intoxicação medicamentosa e alimentar). Depressão: ajuda a combater os sintomas, manutenção da saúde dos ossos e articulações, osteoartrite (ação anti-inflamatória e analgésica).',
        Posologia: 'Encontrada geralmente em cápsulas de 200mg ou intravenosa. Dosagens de 200 a 1600mg/ dia dependendo do tratamento.',
        Reacoes: 'Sintomas como boca seca, náuseas, gases, diarreias, dor de cabeça, agitação e insônia podem ocorrer.',
        ContraInd: 'Gestação e lactação por não terem estudos suficientes da sua ação nas duas situações.',
    },
    {
        ID: 40,
        Suplemento: 'Selênio',
        Descr: 'Suas principais funções são: ação antioxidante, proteção contra ação nociva de metais pesados e xenobióticos, prevenção de doenças crônicas não transmissíveis, elevação da resistência no sistema imunológico e ação como catalisador na produção de hormônio tireoidiano ativo (triiodotironina - T3), aumento do colesterol (HDL), atua na cirrose alcoólica, na atrite reumatoide, na fibrose cística, na insuficiência renal e na distrofia muscular. A deficiência moderada de selênio está associada com o aumento do risco de doenças crônicas, câncer, doenças infecciosas, infertilidade, diminuição da função imune e da tireoide. Suplemento encontrado geralmente em associação a outros minerais e na forma de quelato de selênio.',
        Ind: 'Envelhecimento precoce, prevenção de doenças cardíacas, para estimular sistema imunológico.',
        Posologia: 'Ingestão diária de 55 a 70µg para adultos saudáveis a partir de 19 anos de idade, estima-se que o consumo de 200µg tem ação preventiva contra o câncer.',
        Reacoes: 'O excesso pode causar fadiga muscular, colapso vascular periférico, congestão vascular interna, unhas fracas, queda de cabelo, dermatite, alteração do esmalte dos dentes, vômito',
        ContraInd: 'Para gestantes e nutrizes maior atenção na dosagem.',
    },
    {
        ID: 41,
        Suplemento: 'Silício',
        Descr: 'Mineral importante para a formação de ossos e tecidos conjuntivos (colágeno), para a saúde das unhas, da pele e dos cabelos. Fundamental para a absorção de cálcio, nos estágios iniciais da formação óssea, função moduladora sobre diversas vias metabólicas fundamentais para a homeostase de nosso organismo, especialmente a dérmica, podendo-se considerá-lo um dos recursos mais importantes para a prevenção do câncer de pele. O silício também é necessário para manter as artérias flexíveis e tem papel importante na prevenção de doenças cardiovasculares. O silício se opõe aos efeitos do alumínio no organismo, e é importante na prevenção do Mal de Alzheimer e osteoporose. O boro, cálcio, magnésio, manganês e potássio ajudam na utilização eficiente do silício. O silício é bom para o cabelo porque ajuda no aumento da força, elasticidade, resistência e do volume dos fios de cabelo, reduzindo também a quebra do cabelo.  O silício orgânico é mais bem absorvido pelo organismo. Pode ser associado à vitamina C que também participa da síntese de colágeno. ',
        Ind: 'Pra saúde de cabelos, unhas e pele. Pode ser usado como coadjuvante nos casos de osteoporose, mal de Alzheimer e doenças degenerativas.',
        Posologia: 'Silício orgânico 150mg, pela manhã. Silício elementar 5 a 10 mg.',
        Reacoes: 'Não constam.',
        ContraInd: 'Toxicidade só ocorre se inalado. Em excesso pode contribuir para cálculos renais.',
    },
    {
        ID: 42,
        Suplemento: 'Simbióticos',
        Descr: 'Produto no qual um probiótico e um prebiótico estão combinados, como é o caso, por exemplo, quando um prebiótico como o frutooligossacarídeo é adicionado a um iogurte probiótico. A interação entre o probiótico e o prebiótico in vivo pode ser favorecida por uma adaptação do probiótico ao substrato prebiótico anterior ao consumo. Isto pode, em alguns casos, resultar em uma vantagem competitiva para o probiótico, se ele for consumido juntamente com o prebiótico. Alternativamente, esse efeito simbiótico pode ser direcionado às diferentes regiões “alvo” do trato gastrintestinal, os intestinos delgado e grosso. O consumo de probióticos e de prebióticos selecionados apropriadamente pode aumentar os efeitos benéficos de cada um deles, uma vez que o estímulo de cepas probióticas conhecidas leva à escolha dos pares simbióticos substrato-microrganismo ideais. Efeitos benéficos à saúde Os simbióticos podem ser classificados como componentes dietéticos funcionais que aumentam a sobrevivência dos probióticos durante a passagem pelo trato digestório, pelo fato de seu substrato estar disponível para fermentação. Este efeito simbiótico pode ser direcionado às diferentes regiões- alvo do trato gastrintestinal, os intestinos delgado e grosso. ',
        Ind: 'Síndrome do Intestino Curto e demais doenças intestinais, avaliação individual. Idosos, adultos, pessoas que fazem uso de medicamentos que agridem a flora intestinal (uso de antibióticos por tempo prolongado), portadores de dislipidemias, disbiose intestinal (Constipação/Diarreia), disbiose vaginal e alergias alimentares.',
        Posologia: '1 a 2 sachês dias.',
        Reacoes: 'Desconforto abdominal, flatulência.',
        ContraInd: 'Gestantes, nutrizes e crianças devem acompanhadas com maior atenção.',
    },
    {
        ID: 43,
        Suplemento: 'Vanádio',
        Descr: 'Só recentemente foi considerado essencial à vida humana. Tem uma ação de simular a insulina, favorecendo a entrada de glicose nas células musculares, fígado e tecido adiposo. O seu uso no tratamento de pacientes diabéticos não insulinodependentes tem se apresentado eficiente, por tornar as células periféricas susceptíveis á ação da insulina. O seu uso tem sido estudado também em atletas, com a finalidade de otimizar o transporte e o metabolismo da glicose durante o exercício físico auxiliando no ganho de energia com o maior aporte de glicose para a musculatura. Pode ajudar o corpo a produzir os glóbulos vermelhos. Diminui a formação de colesterol nos vasos sanguíneos, pode prevenir doenças e ataques cardíacos, estimula o crescimento dos tecidos e o metabolismo da gordura.',
        Ind: 'Tratamento coadjuvante das várias formas de diabetes, quanto na medicina esportiva.',
        Posologia: 'As necessidades dietéticas diárias variam entre 10 e 60mcg ao dia. É usado na faixa de 50 – 500mcg ao dia, isoladamente ou em associações multiminerais e vitamínicas.',
        Reacoes: 'Não constam.',
        ContraInd: 'É muito tóxico na superdosagem, podendo causar Síndrome Maníaco-Depressiva, os pacientes devem ser monitorados rotineiramente.',
    },
    {
        ID: 44,
        Suplemento: 'Vitamina A',
        Descr: 'Vitamina lipossolúvel que é estável ao cozimento, porém é destruída pelos raios ultravioletas e processos oxidativos. É pré-formada nos tecidos animais, enquanto que nos tecidos vegetais os precursores são os carotenoides associados à clorofila, sendo transformados em vitamina A no organismo. Essencial para o desenvolvimento e manutenção do tecido epitelial e das mucosas, aos olhos (retina), aumenta a resistência às infecções, saúde reprodutiva, prevenção do câncer, visão noturna. A deficiência causa perda de peso, falta de apetite, má digestão, atraso no crescimento, cegueira noturna, perturbação visual, ressecamento da pele, cabelos e unhas quebradiços.',
        Ind: 'Carência de vitamina A, distúrbios da queratinização (hiperceratoses), alterações mucosas (metaplasia e atrofia), afecções das mucosas das vias aéreas superiores e inferiores, do aparelho digestivo e genito- urinário, tratamento coadjuvante da acne e surdez do ouvido interno.',
        Posologia: 'Deve ser avaliada a carência da vitamina e utilizar conforme fabricante do suplemento.',
        Reacoes: 'Geralmente é bem tolerado, mas pode causar sintomas de hipervitaminose A.',
        ContraInd: 'A suplementação pode causar hipervitaminose A.',
    },
    {
        ID: 45,
        Suplemento: 'Vitamina B1 (Cloridato de Tiamina)',
        Descr: 'A vitamina B1 é fundamental para o metabolismo dos carboidratos, proteínas e gorduras. Por ser essencial ao metabolismo dos carboidratos, quando há grande consumo deste macronutriente ou em situações de grande esforço físico, deve-se aumentar o consumo de tiamina para evitar sinais de deficiência. A tiamina também está envolvida nos processos digestórios, participa da manutenção do apetite e da transmissão de impulsos nervosos. O consumo elevado de álcool interfere na absorção, na  metabolização hepática e aumenta sua excreção renal. Deficiência: Chamada de Beribéri, acomete o sistema nervoso (beribéri seco) o e sistema cardiovascular (beribéri úmido). No beribéri úmido, o acometimento cardíaco caracteriza-se por insuficiência cardíaca. No beribéri seco, ocorrem dois tipos de acometimento do sistema nervoso: polineuropatia periférica e síndrome de Wernicke-Korsakoff. A síndrome de Korsakoff caracteriza-se pela ocorrência de quadro de demência associado à amnésia anterógrada. A deficiência de vitamina B1 também pode ser associada ao alcoolismo e leva a ocorrência da polineuropatia alcoólica. Além dessas doenças pode ocasionar fraqueza muscular e distúrbios cardiovasculares. ',
        Ind: 'Síndrome de Wernicke-Korsakoff, Beribéri (deficiência grave e típica de vitamina B1). ',
        Posologia: '300 a 600 mg/ dia.',
        Reacoes: 'Dor de estômago, calor, inquietação, suor e fraqueza. Reações alérgicas, prurido, dificuldade de respirar, urticária e edema.',
        ContraInd: 'Pacientes com nefropatia, a tiamina é dialisável. Deve-se evitar o uso de bebidas alcoólicas.Não deve ser administrado por períodos prolongados em doses superiores às recomendadas.',
    },
    {
        ID: 46,
        Suplemento: 'Vitamina B12 (Cobalamina)',
        Descr: 'A vitamina B12(hidrossolúvel) é necessária para a formação dos corpúsculos do sangue, do revestimento dos nervos e de várias proteínas. Também está envolvida no metabolismo dos hidratos de carbono e da gordura, é essencial para o crescimento. Existem evidências de que a vitamina B12 é necessária na síntese de coenzimas ativas necessárias na formação do tecido nervoso e na regeneração do ácido fólico durante a formação dos glóbulos vermelhos. A deficiência de essa vitamina é rara, os sintomas demoram a aparecer, e ocorre quando já não existe mais reservas de vitamina no fígado (70% da vitamina sãoarmazenadas nesse órgão). A falta de vitamina B12 leva à anemia megaloblástica (caracterizada por glóbulos vermelhos grandes e imaturos) e a neuropatia nos seres humanos com um estabelecimento insidioso de sintomas. Os grupos de risco para deficiência dessa vitamina são pessoas com anemia perniciosa, pós- cirúrgicos de gastrectomia, pacientes com lesões no intestino grosso, doenças prévias intestinais, pacientes com tratamentos longos com alguns medicamentos, idosos com atrofia gástrica, dieta exclusivamente vegetariana.  ',
        Ind: 'Anemias, deficiência de vitamina B12, coadjuvante de tratamentos de diversas neuropatias sensoriais.',
        Posologia: 'A dose deve se ajustada de acordo com as resposta às doses empregadas e recomendações da DRI. Forma de administração: comprimidos, solução aquosa ou injeção intramuscular.',
        Reacoes: 'Reações de hipersensibilidade tais como sudação, taquicardia e reações cutâneas com prurido e urticária, distúrbios gastrointestinais.',
        ContraInd: 'Gestação de risco, amamentação, atrofia hereditária do nervo óptico, gota, hipersensibilidade a vitamina B12.',
    },
    {
        ID: 47,
        Suplemento: 'Vitamina B2 (Riboflavina)',
        Descr: 'Vitamina hidrossolúvel. Auxilia no crescimento e reprodução, formação da pele, unhas e cabelos saudáveis, combate o cansaço visual, dermatites da face e seborreia. Participa de muitas reações metabólicas dos hidratos de carbono, gorduras, proteínas e na produção de energia através da cadeia respiratória. Atua em diversas reações essenciais de redução de oxidação. Deficiência é rara e geralmente associada a outras vitaminas hidrossolúveis, causa distúrbios no crescimento em crianças. Deficiência séria pode causar escamação da pele, dermatite seborreica. Os grupos de risco de deficiência são pessoas que sofreram algum trauma, como queimaduras e cirurgias, diabetes, hipertireoidismo e cirrose hepática. A má absorção por doenças intestinais podem causar deficiência dessa vitamina.',
        Ind: 'Pacientes com deficiência de vitamina B2 observada em exames.',
        Posologia: '5 a 10mg/dia. Forma de administração: preparados orais, isolada ou em combinações de multivitamínicos ou solução injetável.',
        Reacoes: 'Alterações gastrointestinais.',
        ContraInd: 'Não constam.',
    },
    {
        ID: 48,
        Suplemento: 'Vitamina B3 (Niacina, Nicotinamida, Ácido Nicotínico)',
        Descr: 'Vitamina hidrossolúvel. Atua na síntese e no metabolismo de gorduras e oxigenação dos tecidos, é essencial na biossíntese dos hormônios sexuais, é necessária a um sistema nervoso saudável e para um bom desempenho das funções cerebrais. Indicada para tratamento de colesterol e triglicerídeos',
        Ind: 'Prevenir doenças como Alzheimer, catarata e aterosclerose. Melhorar o controle da diabetes e baixar os níveis de colesterol.',
        Posologia: 'Crianças 2 a mg/dia. Homens e Mulheres 16 a 18 mg/dia.',
        Reacoes: 'Podem causar efeitos colaterais como formigamento, dor de cabeça, coceira e vermelhidão na pele.',
        ContraInd: 'IH significativa, úlcera péptica ativa ou sangramento arterial, lactação.',
    },
    {
        ID: 49,
        Suplemento: 'Vitamina B5 (Ácido Pantotênico)',
        Descr: 'Vitamina hidrossolúvel. Importante no organismo por ser um dos componentes da coenzima A, participa de processos comometabolismo de proteínas, gorduras e carboidratos, a produção de energia, e a síntese das células vermelhas e Acetilcolina. A deficiência isolada dessa vitamina é rara e os sintomas são pouco conhecidos',
        Ind: 'É indicada para tratamento de reações alérgicas, cansaço, cicatrização, infecções respiratórias. Alguns estudos mostram que pode ajudar a manter níveis de colesterol e triglicerídeos dentro da faixa da normalidade. É indicada também para atletas e praticantes de atividades físicas por participar de produção de energia.',
        Posologia: 'De acordo com a DRIs.',
        Reacoes: 'Dosagens altas podem ocasionar diarreia.',
        ContraInd: 'Gestantes, pacientes com hemofilia.',
    },
    {
        ID: 50,
        Suplemento: 'Vitamina B6 (Piridoxina)',
        Descr: 'Vitamina hidrossolúvel, Sua principal função é como coenzima. Papel importante no metabolismo de proteínas, carboidratos e lipídios. A deficiência dessa vitamina é rara, geralmente associada a outras vitaminas. Quando apresentada a deficiência pode levar a anemia hipocrômica, prejuízo na produção de eritrócitos.',
        Ind: 'Sintomas de náuseas e vômitos durante os meses iniciais da gravidez, durante o decurso da gravidez e amamentação. Utilizada também para ajudar no alívio da depressão (nas mulheres que tomam contraceptivos orais) e na tensão pré- menstrual.',
        Posologia: 'De acordo com as DRIs. Geralmente é encontrada na forma de hidrocloreto de piridoxina.',
        Reacoes: 'São raras, mas podem se manifestar com acidez estomacal com doses altas.',
        ContraInd: 'Pacientes com hipersensibilidade a vitamina. Doses altas (valores acima de 500mg) e por períodos prolongados (anos) pode ocasionar Neuropatia Periférica, alterações sensoriais, ataxia e fraqueza muscular; doses elevadas (2. 000- 6. 000 mg/ dia) pode causar perturbações nervosas. Doses inferiores a 200mg/ dia são bem toleradas.',
    },
    {
        ID: 51,
        Suplemento: 'Vitamina B9 (Ácido Fólico)',
        Descr: 'É essencial na formação de glóbulos vermelhos e na síntese dos ácidos nucléicos e da colina, regula o desenvolvimento das fibras nervosas na fase embrionária fetal; é armazenado no fígado em mínimas quantidades, mas é rapidamente excretado pelo rim em grandes quantidades, em 24horas. Sua deficiência causa anemia, lesões nas mucosas, distúrbios intestinais, alterações na medula óssea. ',
        Ind: 'Tratamento de anemia megaloblástica associada à deficiência de Ácido Fólico, suplemento para prevenção do defeito do tubo neural na gravidez, profilaxia e tratamento em situações de deficiência de ácido fólico, como estados hemolíticos crônicos ou em diálise renal.',
        Posologia: '5mg, uma vez ao dia e conforme DRIs.',
        Reacoes: 'Geralmente é bem tolerado, pode causar quadros alérgicos e desconforto gástrico. Doses elevadas podem produzir alterações no SNC e podem comprometer a absorção intestinal de zinco, levar uma precipitação de cristais de ácido fólico nos rins. ',
        ContraInd: 'Hipersensibilidade ao ácido fólico pacientes com anemia perniciosa.',
    },
    {
        ID: 52,
        Suplemento: 'Vitamina C (ácido ascórbico)',
        Descr: 'Contribui para o fortalecimento do sistema imunológico, para a melhora da cicatrização, para a absorção de ferro e para conservação de tecidos e vasos. Participa da formação de colágeno, efeito antioxidante. Sua deficiência causa escorbuto, doença que provoca fraqueza, dores articulares e musculares, sangramento na gengiva, amolecimento dos dentes. Doses altas (5.000mg/dia) podem provocar gases e diarreia, escorbuto de rebote e cálculos renais em pacientes com predisposição. Suplemento encontrado em comprimidos efervescentes, solução oral, ampola.',
        Ind: 'Tratamento e profilaxia de gripes e resfriados, suplemento nutricional na gestação, lactação, atividades desportivas, doenças infecciosas, estados febris, deficiência de vitamina C (escorbuto), tratamento da metemoglobinemia idiopática.',
        Posologia: 'Verificar DRIs e tipo de tratamento.',
        Reacoes: 'São raras e com pouca intensidade: náuseas, vômitos, diarreias e aumento da diurese.',
        ContraInd: 'Pacientes portadores de litíase urinária e oxálica úrica.',
    },
    {
        ID: 53,
        Suplemento: 'Vitamina D',
        Descr: 'Vitamina lipossolúvel é ativada no organismo pela ação do sol (raios ultravioletas sobre a pele). Tem como função a regulação do metabolismo do cálcio e do fósforo a nível intestinal e ósseo, ajuda na fixação desses minerais nos dentes e ossos. Quando há insuficiência de cálcio na dieta a vitamina D é responsável por retirar o cálcio dos ossos para o organismo. É essencial para crianças, na gravidez e na amamentação.  Deficiência de vitamina D causa raquitismo quando na infância, osteomalacia em adultos, osteoporose em idosos, cáries dentárias, hiperparatireoidismo secundário. O excesso causar anorexia, náuseas, vômitos, dores de cabeça, constipação ou diarreia, fadiga, perda de apetite, sede e urinação excessiva, proteína na urina, danos hepáticos e renais, hipercalcemia. Suplemento de vitamina D encontrado na forma de vitamina D2 e D3 podem ser em comprimidos ou em solução lipossolúvel.',
        Ind: 'Carência de Vitamina D, para idosos, casos de pré- menopausa e menopausa, osteopenia e osteoporose, hipoparatireoidismo, raquitismo.',
        Posologia: 'Deve ser avaliado conforme dosagem sanguínea e indicação de tratamento.',
        Reacoes: 'Ocorrem quando presente hipervitaminose D. Comum: dor de cabeça, náusea, dor abdominal.',
        ContraInd: 'É contraindicado também em pacientes que apresentam hipervitaminose D, elevadas taxas de cálcio ou fosfato na corrente sanguínea e também em casos de má-formação nos ossos.',
    },
    {
        ID: 54,
        Suplemento: 'Vitamina E (Tocoferol)',
        Descr: 'Vitamina lipossolúvel, antioxidante (inibe ou retarda a oxidação do tecido animal) inibe radicais livres, principalmente de origem tecidual gorduroso, tem efeito protetor contra processos neurológicos (muito utilizada para geriatria), aumenta a atividade imunológica do organismo, protetor contra doenças cardíacas, melhora câimbras musculares, reduz sintomas de tensão pré- menstrual (TPM) quando associada a vitamina B6, protetora intracelular, previne aborto ou parto prematuro, melhora circulação geral. Sua deficiência causa distrofias musculares, problemas na reprodução, em prematuros pode causar anemia hemolítica por baixo nível de vitamina E aumenta a hemólise de eritrócitos. Suplementação geralmente encontrada em cápsulas gelatinosas. ',
        Ind: 'Para ação antioxidante, falta de vitamina E, dietas restritivas e inadequadas, coadjuvante no tratamento das afecções musculares e do tecido conjuntivo.',
        Posologia: 'De acordo com a indicação de tratamento e fabricante.',
        Reacoes: 'Geralmente não é tóxica, em excesso pode causar desconforto estomacal, vertigens e diarreia.',
        ContraInd: 'Doses elevadas podem reduzir a absorção de vitamina A e K. A vitamina E atravessa a barreira placentária e doses acima da DRI recomendada não devem ser utilizadas durante a gravidez sem prescrição médica.',
    },
    {
        ID: 55,
        Suplemento: 'Vitamina K',
        Descr: 'Atua no fígado onde auxilia no processo de coagulação normal do sangue. Sua deficiência é rara, pois é encontrada nos alimentos e as bactérias do intestino produzem vitamina K. Quando deficiente devido a causas patológicas pode provocar aumento do tempo de coagulação do sangue e hemorragia. Pode haver deficiência em recém-nascidos porque a flora intestinal não sintetiza essa vitamina em quantidades adequadas, devido a isso durante a gestação as mães devem ter o cuidado com a ingestão adequada dessa vitamina. Pode ser encontrada com os nomes: filoquinona, menaquinona e menadiona, em soluções injetáveis intramusculares ou intravenosas. ',
        Ind: 'Distúrbios de coagulação, hemorragia, hemorragia por hipoprotrombinemia grave.',
        Posologia: 'De acordo com o tratamento e indicação.',
        Reacoes: 'Geralmente não é tóxica pode causar um tipo de icterícia em crianças prematuras.',
        ContraInd: 'Nos três primeiros meses de gestação, hipersensibilidade à vitamina K.',
    },
    {
        ID: 56,
        Suplemento: 'Whey Protein',
        Descr: 'Whey Protein é a proteína isolada do soro do leite, possui baixo peso molecular e alto valor biológico, sendo mais bem aproveitada pelo organismo. No Whey Protein estão presentes todos os aminoácidos necessários para síntese proteica. Traz vários benefícios ao organismo como a melhora da imunidade, em doses corretas previne o envelhecimento precoce por elevar as concentrações de glutationa, diminuindo, assim, a ação dos agentes oxidantes nos músculos esqueléticos, e doenças como câncer diabetes e hipertensão arterial. Contribui para o ganho de massa muscular sendo muito utilizado por atletas e praticantes de atividade física. O whey protein pode ser utilizado também para pacientes submetidos à radioterapia ou quimioterapia que não conseguem suprir as necessidades nutricionais diárias devido a náuseas e falta de apetite, para pacientes com diabetes porque a proteína do soro do leite ajuda a controlar os níveis de glicose no sangue, para o envelhecimento saudável uma vez que as pessoas mudam sua alimentação ao se tornarem idosas, ingerindo menos proteína e nutrientes necessários, e para cicatrização pós-cirurgia ou queimaduras, pois nesses casos uma quantidade insuficiente de proteínas retarda o processo de cura.',
        Ind: 'Sarcopenia, auxiliar em dietas, fórmulas infantis, uso pós-operatório, suplemento para praticantes de atividade física. Suplemento alimentar para pacientes com: hipertensão arterial, doenças infecciosas, câncer, doenças hepáticas, doenças cardíacas.',
        Posologia: 'Para praticantes de exercícios moderados, o indicado é de 1,2g a 1,8g por quilo corporal, atletas de alto nível devem consumir de 1,6 a 2,4g por quilo corporal dependendo da modalidade. Para pacientes doentes é necessário avaliação da alimentação individual para incluir o suplemento.',
        Reacoes: 'Em algumas pessoas pode provocar gases. ',
        ContraInd: 'O excesso é excretado nas fezes. Pode contribuir para o ganho de peso se não for ingerida a dosagem correta ou se o uso não for acompanhado de uma dieta equilibrada. Há estudos que indicam que o excesso de proteínas contribui para lesão e doenças renais quando o uso é prolongado.',
    },
    {
        ID: 57,
        Suplemento: 'Zinco',
        Descr: 'Intervém no controle cerebral dos músculos e no metabolismo de proteínas e carboidratos, auxilia na oxigenação dos tecidos. Tem função de desintoxicação alcoólica, síntese imunológica, síntese proteica, atua no metabolismo celular e dos ossos, participa da maturação sexual, metabolismo da vitamina B1, A e D, produção de energia. Cerca de 200 enzimas do corpo precisam do zinco com catalisador. Sua deficiência causa alterações no olfato e paladar, acne, perda de cabelos, atraso no desenvolvimento sexual, diminuição da visão noturna, impotência, atraso no crescimento. Suplemento encontrado nas seguintes formas: óxido de zinco e sulfato de zinco.',
        Ind: 'Ação antioxidante, reparação celular, cicatrização, baixa imunidade, infertilidade, déficit de crescimento, cabelos e unhas fracas, acne, fadiga.',
        Posologia: 'Verificar DRIs e formulação escolhida.',
        Reacoes: 'Ocorre em doses excessivas, podendo ocasionar náuseas e vômitos, dor abdominal diminuição na coordenação motora.',
        ContraInd: 'Hipersensibilidade ao suplemento escolhido. Pode interferir na absorção de ferro e cobre, pois o zinco compete com esses minerais no intestino.',
    }
]